### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ovgamesdev** [yausername/youtubedl-android#114]
-o/storage/0000-0000/yt/%(title)s.%(exc)s https://www.youtube.com/c/?
this is the way to my SD card
![Screenshot_2021-07-21-13-04-09-04_dbcbfa4e931621cb5fc89641b4706bb7](https://user-images.githubusercontent.com/56827421/126446739-a9bb73ef-0926-4e05-8911-20869aceab70.jpg)
![Screenshot_2021-07-21-13-04-47-12](https://user-images.githubusercontent.com/56827421/126446742-f6f575a3-ab8a-45dc-ae07-abdace8be3fb.jpg)

**Comment by kairusds** [comment]
If you're on Android 10, write access to sdcard is not possible unless the library uses FileProvider.

**Comment by xibr** [comment]
You need to use the Storage Access Framework to allow app to store data on an external sdcard.
