### ISSUE TITLE
not working when building bundle android

### ISSUE THREAD

**Issue by raj02dec** [yausername/youtubedl-android#116]
C:\Users\LENOVO\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-strip.exe: error: 'E:\InsureBrand365-master\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libpython.zip.so': The file was not recognized as a valid object file

**Comment by kientux** [comment]
I'm still facing this issue when build release, is there any way to fix this?

```
.../Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip: error: '.../build/app/intermediates/merged_native_libs/prodRelease/out/lib/arm64-v8a/libffmpeg.zip.so': The file was not recognized as a valid object file
```

**Comment by kientux** [comment]
This happens when build AAB instead of APK. Add this `packagingOptions` to build.gradle should fix the issue.

```
android {
    ...
    
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}
```

**Comment by zhangyinglong1993** [comment]
> 构建 AAB 而不是 APK 时会发生这种情况。将其添加`packagingOptions`到 build.gradle 应该可以解决问题。
> 
> ```
> android {
>     ...
>     
>     packagingOptions {
>         jniLibs {
>             useLegacyPackaging = true
>         }
>     }
> }
> ```

That doesn't seem to work either
