### ISSUE TITLE
Replace youtube-dl with yt-dlp

### ISSUE THREAD

**Issue by ghost** [yausername/youtubedl-android#117]
I suggest you to replace youtube-dl with its successor yt-dlp, because the youtube-dl repository has long been dead and the program partially no longer works, while yt-dlp is actively developing.

Project repository: https://github.com/yt-dlp/yt-dlp

Two issues about the status of the youtube-dl: https://github.com/ytdl-org/youtube-dl/issues/30022 and https://github.com/ytdl-org/youtube-dl/issues/29965

**Comment by xibr** [comment]
So far we don't know if youtube-dl really won't be maintained, also it's still working.

**Comment by K3XRad** [comment]
Sounds reasonable at the moment. I think you could make the final decision only in the future, when, for example, youtube-dl stop working. So it is better to leave this issue open.

**Comment by stooged** [comment]
i found that using this repo with the original youtube-dl resource it ended up being unusable so i just switched to the yt-dlp resource with this repo and can confirm it is working perfectly again

**Comment by xibr** [comment]
This patch solves the issue.  https://github.com/ytdl-org/youtube-dl/pull/30184

**Comment by xibr** [comment]
updated youtube-dl binary https://github.com/yausername/youtubedl-lazy/releases/download/2021.06.06/youtube_dl.zip To apply the changes you must remove the app data and then update youtube-dl from the app.

**Comment by TechComet** [comment]
+1

**Comment by xibr** [comment]
Should we switch to yt-dlp?
@yausername what do you think? 

ytdlp-lazy
https://github.com/xibr/ytdlp-lazy

Test yt-dlp
https://github.com/xibr/youtubedl-android/tree/switch_to_yt_dlp

**Comment by stooged** [comment]
yt-dlp has been working great for me.
if you do not make the switch then maybe make a branch for yt-dlp.

**Comment by xibr** [comment]
> yt-dlp has been working great for me. if you do not make the switch then maybe make a branch for yt-dlp.

Yes it is, I added PR #120 to switch to yt-dlp 
but before that, let's know what @ yausername's  thinks.

**Comment by TechComet** [comment]
> > yt-dlp has been working great for me. if you do not make the switch then maybe make a branch for yt-dlp.
> 
> Yes it is, I added PR #120 to switch to yt-dlp but before that, let's know what @ yausername's thinks.

I try your repo (befor last update) ... it's work
https://github.com/xibr/youtubedl-android/tree/switch-to-yt-dlp

it's work but I not found it on any repository
and found some problem when build it .. for this I import project files in my project direct
please add package on jitpack.io or mvnrepository .. soon

**Comment by xibr** [comment]
Build failed on my fork and in original repo. I will look into the problem later
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ffmpeg:stripReleaseDebugSymbols'.
> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.1.6352462

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
22 actionable tasks: 17 executed, 5 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
ERROR: Time-out getting container status
Error building
```

**Comment by TechComet** [comment]
`> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.1.6352462`

install ndk version `21.0.6113669` or change ndk version in project to `21.1.6352462`

**Comment by xibr** [comment]
> install ndk version `21.0.6113669` or change ndk version in project to `21.1.6352462`

The local build was successful, I meant the build on jitpack.

**Comment by xibr** [comment]
@TechComet BUILD SUCCESSFUL [switch-to-yt-dlp-0.1.0-g48806d1-92/build.log](https://jitpack.io/com/github/xibr/youtubedl-android/switch-to-yt-dlp-0.1.0-g48806d1-92/build.log)

[jitpack.io/#xibr/youtubedl-android](https://jitpack.io/#xibr/youtubedl-android/48806d1299)

```
implementation 'com.github.xibr.youtubedl-android:library:switch-to-yt-dlp-SNAPSHOT'
implementation 'com.github.xibr.youtubedl-android:ffmpeg:switch-to-yt-dlp-SNAPSHOT'
```
or
```
implementation 'com.github.xibr.youtubedl-android:library:48806d1299'
implementation 'com.github.xibr.youtubedl-android:ffmpeg:48806d1299'
```

**Comment by xibr** [comment]
added branch for yt-dlp

The [yt-dlp branch](https://github.com/yausername/youtubedl-android/tree/yt-dlp) was added in the original repo and the usage method was added in the [readme file](https://github.com/yausername/youtubedl-android#gradle).

```gradle
dependencies {
    implementation 'com.github.yausername.youtubedl-android:library:13a5502c80'
    implementation 'com.github.yausername.youtubedl-android:ffmpeg:13a5502c80'
}
```

**Comment by yausername** [comment]
@xibr sorry for the delayed reply. I am fine with the move. I can help review PRs if you create any.
Awesome work!

**Comment by xibr** [comment]
> @xibr sorry for the delayed reply. I am fine with the move. I can help review PRs if you create any.
> Awesome work!

well, I'll do that maybe before the weekend.
