### ISSUE TITLE
File size output problem

### ISSUE THREAD

**Issue by yyms3275** [yausername/youtubedl-android#122]
Below is the output of the result. Always the same 720p video file size is 0.

 VideoInfo streamInfo = YoutubeDL.getInstance().getInfo("youtube url");

streamInfo(getExt) : mp4
streamInfo(getFormatNoteitem) : 720p
streamInfo(getWidth) : 1280
streamInfo(getHeight) : 720
**streamInfo(getFilesize) : 0**
streamInfo(getFormatId) : 22
streamInfo(getFormat) : 22 - 1280x720 (720p)
streamInfo(getAcodec) : mp4a.40.2
streamInfo(getVcodec) : avc1.64001F
streamInfo(getFps) : 30
streamInfo(getAbr) : 0
streamInfo(getTbr) : 346

**Comment by xibr** [comment]
this issue is not related to this library, if you try to get the video info with the youtube-dl command `youtube-dl --dump-json url` you will get file size=null in format_id 22 & format_note 720p

```json
{
         "asr":44100,
         "filesize":null,
         "format_id":"22",
         "format_note":"720p",
         "fps":25,
         "height":720,
         "quality":4,
         "tbr":1613.0,
         "url":"https://r3---sn-vh5ouxa-hjud.googlevideo.com/videoplayback?expire....",
         "width":1280,
         "ext":"mp4",
         "vcodec":"avc1.64001F",
         "acodec":"mp4a.40.2",
         "format":"22 - 1280x720 (720p)",
         "protocol":"https"
}
```

**Comment by yyms3275** [comment]
Thank you for answer.

**Comment by yyms3275** [comment]
> this issue is not related to this library, if you try to get the video info with the youtube-dl command `youtube-dl --dump-json url` you will get file size=null in format_id 22 & format_note 720p
> 
> ```json
> {
>          "asr":44100,
>          "filesize":null,
>          "format_id":"22",
>          "format_note":"720p",
>          "fps":25,
>          "height":720,
>          "quality":4,
>          "tbr":1613.0,
>          "url":"https://r3---sn-vh5ouxa-hjud.googlevideo.com/videoplayback?expire....",
>          "width":1280,
>          "ext":"mp4",
>          "vcodec":"avc1.64001F",
>          "acodec":"mp4a.40.2",
>          "format":"22 - 1280x720 (720p)",
>          "protocol":"https"
> }
> ```

Thank you for answer.
