### ISSUE TITLE
Unable to find the libary in repository

### ISSUE THREAD

**Issue by Rujengelal** [yausername/youtubedl-android#124]
Could not find any matches for com.github.yausername.youtubedl-android:library:0.13.+ as no versions of com.github.yausername.youtubedl-android:library are available.
Required by:
    project :app

**Comment by xibr** [comment]
Have you added a jitpack repository?

**Comment by Rujengelal** [comment]
yes it is as follows
`// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {

        google()

        mavenCentral()
        maven { url 'https://jitpack.io' }

    }

    dependencies {
        classpath "com.android.tools.build:gradle:7.0.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.20"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}




task clean(type: Delete) {
    delete rootProject.buildDir
}`

**Comment by xibr** [comment]
Add it in allprojects

```gradle
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

See this file https://github.com/yausername/dvd/blob/master/build.gradle
