### ISSUE TITLE
Long video to MP3 conversion problem

### ISSUE THREAD

**Issue by yyms3275** [yausername/youtubedl-android#127]
I proceeded with the setting below for the YouTube address below. However, after 98.7% of the download process, there was no response and the process stopped. The log also did not come out of the stopped state. May I know what the problem is?

* Test url : https://youtu.be/rY_B7XIQeKk

[code option]

YoutubeDLRequest request = new YoutubeDLRequest("YOUTUBE URL");
request.addOption("--no-mtime");
request.addOption("-f", "22");
request.addOption("--extract-audio");
request.addOption("--audio-quality", "5");
request.addOption("--audio-format", "mp3");
request.addOption("-o", "SAVE PATH");

**Comment by xibr** [comment]
Maybe you have a problem with your code, I'm assuming the app stops working in the background maybe that's why your download stops.

Also if you want to download mp3 you don't need this `request.addOption("-f", "22");`

**Comment by yyms3275** [comment]
Thank you for answer. I am using the library very well. Thank you for making it.
