### ISSUE TITLE
Process log related to MP3 conversion

### ISSUE THREAD

**Issue by yyms3275** [yausername/youtubedl-android#128]
When converting MP3, can you know the process of conversion? In the case of download, it can be known by the corresponding callback of YoutubeDL.getInstance().execute(request, callback) , but I do not know the progress of MP3 conversion. Is there a way?

**Download code :**

YoutubeDLRequest request = new YoutubeDLRequest("YOUTUBE_URL");
request.addOption("--no-mtime");
 request.addOption("--extract-audio");
request.addOption("--audio-quality", "5");
request.addOption("--audio-format", "mp3");
request.addOption("-o", "SAVE_PATH");

Disposable disposable = Observable.fromCallable(() -> YoutubeDL.getInstance().execute(request, callback))
   .subscribeOn(Schedulers.newThread())
   .observeOn(AndroidSchedulers.mainThread())
   .subscribe(youtubeDLResponse ->
   {
      //download successful
   }, e ->
    {
      //failed to download
   });

private final DownloadProgressCallback callback = new DownloadProgressCallback()
{
        @Override
        public void onProgressUpdate(float progress, long etaInSeconds)
        {
           //progress + "% (ETA " + etaInSeconds + " seconds)");
        }
};

**Comment by xibr** [comment]
No, because youtube-dl doesn't provide it so you can't figure it out, also when you try to convert long videos it may take longer.
