### ISSUE TITLE
Not Working for OpenLoad videos

### ISSUE THREAD

**Issue by umair-iqbal-ct** [yausername/youtubedl-android#13]
Not Working with Open Load videos: getting error
ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org

**Comment by xibr** [comment]
Openload shut down in 2019 see [https://en.m.wikipedia.org/wiki/Openload](https://en.m.wikipedia.org/wiki/Openload), so I'm closing. Please feel free to open a new issue if you find another bug.
