### ISSUE TITLE
Youtube Download speed is capped

### ISSUE THREAD

**Issue by chaikovskiy99** [yausername/youtubedl-android#131]
For some reason download speed does not go beyond 80kbps, with youtube, it's always the same. I am on 170mbps connection. I have created android app using the library. For every download, the speed is around 80kbps.

**Comment by xibr** [comment]
We have switched to yt-dlp, Are you using the latest version?

**Comment by chaikovskiy99** [comment]
> We have switched to yt-dlp, Are you using the latest version?

No, I think I am using old repo, I will try and update, thanks for info.
