### ISSUE TITLE
Doesnt work when app published on google play

### ISSUE THREAD

**Issue by cleph** [yausername/youtubedl-android#133]
I couldnt change target version to 29 cuz play store dont agree that and it crashes when download it from google play anyone can help me its ver necessary for me thanks

**Comment by xibr** [comment]
Maybe #76 or #88 will help you.

**Comment by lucasfvc** [comment]
add the following proguard rule
`-keep class com.yausername.youtubedl_android.** { *; }`
I solved this problem this way

**Comment by NewMacPro** [comment]
> I couldnt change target version to 29 cuz play store dont agree that and it crashes when download it from google play anyone can help me its ver necessary for me thanks

IsIs there a problem with launching the Google play store?
Can it be used?
Will Google delete applications or block accounts?

**Comment by zhangyinglong1993** [comment]
> 添加以下 proguard 规则 `-keep class com.yausername.youtubedl_android.** { *; }` 我通过这种方式解决了这个问题

Is it okay now?
