### ISSUE TITLE
How to save file format to mp4?

### ISSUE THREAD

**Issue by EdgeServerless** [yausername/youtubedl-android#138]

**Comment by xibr** [comment]
Please add some details what you would like to do, if you mean in the sample app the files are saved as mp4.

**Comment by EdgeServerless** [comment]
when download youtube file, current file format is webm,but i want save file format is mp4.

**Comment by xibr** [comment]
try use config file [https://github.com/yausername/youtubedl-android#sample-app](https://github.com/yausername/youtubedl-android#sample-app) 

or use command line 

```
-f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -o /sdcard/Download/youtubedl-android/%(title)s.%(ext)s url
```
