### ISSUE TITLE
getVideoUrl(VideoInfo streamInfo)

### ISSUE THREAD

**Issue by HasanElHefnawy** [yausername/youtubedl-android#14]
In StreamingExampleActivity.java, there is a method getVideoUrl(VideoInfo streamInfo). I think it will be nice if it's moved to VideoInfo class. You can also add it in README.md for those who are looking for this method. Actually, there are many posts on stackoverflow that look for such a method. And, many thanks to you for this awesome library.

**Comment by yausername** [comment]
The `getVideoUrl` method in `StreamingExampleActivity.java` is just as an example. To fetch video url you need multiple parameters like format, quality, bitrate, audio, video, etc. It also differs across different services. So it would be better to leave it to the users of the library.
That being said, I might look into it if there is a standard way of fetching url.

**Comment by yausername** [comment]
A single playable link containing audio+video can be obtained like this
```java
YoutubeDLRequest request = new YoutubeDLRequest(url);
request.addOption("-f", "best");
VideoInfo streamInfo = YoutubeDL.getInstance().getInfo(request);
System.out.println(streamInfo.getUrl());
```
See [this](https://github.com/yausername/youtubedl-android/blob/master/app/src/main/java/com/yausername/youtubedl_android_example/StreamingExampleActivity.java) for more.
