### ISSUE TITLE
can't convert to m4a / downloading  directly as mp3

### ISSUE THREAD

**Issue by BatuhanAkar** [yausername/youtubedl-android#142]
request.addOption("--downloader","ffmpeg");
            request.addOption( "--audio-format","m4a");
            request.addOption(" --extract-audio","-x");

            request.addOption("-o", youtubeDLDir.getAbsolutePath() + "/%(title)s.%(ext)s");

**Comment by xibr** [comment]
Are you trying to download from YouTube?  If yes, why do you want to convert to m4a when YouTube provides m4a audio.

**Comment by astroncc** [comment]
request.addOption("--extract-audio");
request.addOption("--audio-quality", "5");
request.addOption("--audio-format", "mp3");
request.addOption("-o", file.getPath());

**Comment by BatuhanAkar** [comment]
> Are you trying to download from YouTube? If yes, why do you want to convert to m4a when YouTube provides m4a audio.

i want to convert to for  low file size.  file extension   m4a , but as  filetype saving mp3.
  i just need audio  file and  embedded thumbnail required,how can i use "atomicparlsey"  ?

**Comment by xibr** [comment]
> i want to convert to for low file size. file extension m4a , but as filetype saving mp3. i just need audio file and embedded thumbnail required,how can i use "atomicparlsey" ?

See my comment https://github.com/yausername/youtubedl-android/issues/121#issuecomment-1124502418

**Comment by xibr** [comment]
Thumbnail embedding is done via ffmpeg and mutagen We have added mutagen in the latest commit.
