### ISSUE TITLE
Failed to Build, Cannot resolve Library and FFmpeg dependencies

### ISSUE THREAD

**Issue by deniscerri** [yausername/youtubedl-android#149]
> Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform library-0.13.1.jar (com.github.yausername.youtubedl-android:library:0.13.1) to match attributes {artifactType=android-jni, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find library-0.13.1.jar (com.github.yausername.youtubedl-android:library:0.13.1).
        Searched in the following locations:
            https://jitpack.io/com/github/yausername/youtubedl-android/library/0.13.1/library-0.13.1.jar
   > Failed to transform ffmpeg-0.13.1.jar (com.github.yausername.youtubedl-android:ffmpeg:0.13.1) to match attributes {artifactType=android-jni, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find ffmpeg-0.13.1.jar (com.github.yausername.youtubedl-android:ffmpeg:0.13.1).
        Searched in the following locations:
            https://jitpack.io/com/github/yausername/youtubedl-android/ffmpeg/0.13.1/ffmpeg-0.13.1.jar
            
![image](https://user-images.githubusercontent.com/64997243/168427693-e929aefd-29c9-4edf-b3a4-03cd040b5a20.png)
![image](https://user-images.githubusercontent.com/64997243/168427721-27e07024-3823-4d43-93c7-2b440f85142c.png)

Tried a Kotlin version but same errors pop up

**Comment by BatuhanAkar** [comment]
> > Execution failed for task ':app:mergeDebugNativeLibs'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Failed to transform library-0.13.1.jar (com.github.yausername.youtubedl-android:library:0.13.1) to match attributes {artifactType=android-jni, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
> > > Could not find library-0.13.1.jar (com.github.yausername.youtubedl-android:library:0.13.1).
> > Searched in the following locations:
> > https://jitpack.io/com/github/yausername/youtubedl-android/library/0.13.1/library-0.13.1.jar
> > Failed to transform ffmpeg-0.13.1.jar (com.github.yausername.youtubedl-android:ffmpeg:0.13.1) to match attributes {artifactType=android-jni, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
> > > Could not find ffmpeg-0.13.1.jar (com.github.yausername.youtubedl-android:ffmpeg:0.13.1).
> > Searched in the following locations:
> > https://jitpack.io/com/github/yausername/youtubedl-android/ffmpeg/0.13.1/ffmpeg-0.13.1.jar
> 
> ![image](https://user-images.githubusercontent.com/64997243/168427693-e929aefd-29c9-4edf-b3a4-03cd040b5a20.png) ![image](https://user-images.githubusercontent.com/64997243/168427721-27e07024-3823-4d43-93c7-2b440f85142c.png)
> 
> Tried a Kotlin version but same errors pop up

------------------------------------------------------------
try the updated version 

implementation 'com.github.yausername.youtubedl-android:library:6346beb6d7'
implementation 'com.github.yausername.youtubedl-android:ffmpeg:6346beb6d7'

**Comment by deniscerri** [comment]
`implementation 'com.github.yausername.youtubedl-android:library:6346beb6d7'`
`implementation 'com.github.yausername.youtubedl-android:ffmpeg:6346beb6d7'`

This one worked. Thank you.

The other one gave me the same error though.

**Comment by BatuhanAkar** [comment]
@deniscerri do you have an idea ? #151

**Comment by deniscerri** [comment]
> @deniscerri do you have an idea ? #151

I am facing the same issue right now. The file starts to download but then it errors out as soon as it tries to convert webm files into mp4 or mp3.

**Comment by BatuhanAkar** [comment]
- [ ]  request.addOption("--no-mtime");
- [ ] request.addOption("--extract-audio");
- [ ] request.addOption("--audio-format" );
- [ ] request.addOption("m4a");
- [ ] request.addOption("--add-metadata");
- [ ] request.addOption("--write-thumbnail");
- [ ] request.addOption("-f", "bestaudio[ext=m4a]");
- [ ] request.addOption("-o", youtubeDLDir.getAbsolutePath() + "/%(title)s.%(ext)s");
- [ ] request.addOption("--embed-thumbnail");

in this way successfully  .mp3 file and .PNG image and  .WEBP image downloading but to not successfully thumbnail embedded. i take here error.

**Comment by BatuhanAkar** [comment]
also you can download directly mp4 this way

            request.addOption("--no-mtime");
            request.addOption("-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best");
            request.addOption("-o", youtubeDLDir.getAbsolutePath() + "/%(title)s.%(ext)s");
