### ISSUE TITLE
Failed to resolve: library-0.13.1 Affected Modules: app

### ISSUE THREAD

**Issue by mazrou** [yausername/youtubedl-android#155]
I'm trying to use the library module by this 

```gradle
repositories {
        maven { url 'https://jitpack.io' }
    }
``` 

```gradle
implementation 'com.github.yausername.youtubedl-android:library:0.13.1'
``` 

I could not get the library and I get the error
`Failed to resolve: library-0.13.1 Affected Modules: app`

because it searchs in this link 
https://jitpack.io/com/github/yausername/youtubedl-android/library/0.12.4/library-0.12.4.jar.

but the real link to the library is : 
https://jitpack.io/com/github/yausername/youtubedl-android/library/0.12.4/library-0.12.4-sources.jar

I do not know if I can change the it in my project , or fix it from your part.

@xibr @yausername  @tinybug

**Comment by willsmithgranzer** [comment]
Same Error! Have You Find Any Solution?

**Comment by xibr** [comment]
@mazrou @willsmithgranzer check this answer https://stackoverflow.com/a/69474372

Use this if the issue is not resolved
```
implementation 'com.github.yausername.youtubedl-android:library:-SNAPSHOT'
implementation 'com.github.yausername.youtubedl-android:ffmpeg:-SNAPSHOT'
```

instead of 

```
implementation 'com.github.yausername.youtubedl-android:library:0.13.1'
implementation 'com.github.yausername.youtubedl-android:ffmpeg:0.13.1'
```

**Comment by bryan121211** [comment]
Pudieron resolver el problema???

**Comment by bryan121211** [comment]
en donde se pone eso
