### ISSUE TITLE
Failed to resolve: library-0.13.1 or library:-SNAPSHOT

### ISSUE THREAD

**Issue by xyzPrimeTV** [yausername/youtubedl-android#161]
Hello All,

I am facing issue similar to #155.

But the solution provided below is not working at the moment:
implementation 'com.github.yausername.youtubedl-android:library:-SNAPSHOT'
implementation 'com.github.yausername.youtubedl-android:ffmpeg:-SNAPSHOT'

Is there any other solution to resolve this issue ?

Thanks in advance.

**Comment by HsuHsiaoHsuan** [comment]
I use `-0.13.1-ga41cfdf-7`
