### ISSUE TITLE
Set ffmpeg location and update yt-dlp directly from yt-dlp repo

### ISSUE THREAD

**Issue by xibr** [yausername/youtubedl-android#175]
We will replace the current yt-dlp updates method and make it directly from the yt-dlp repo because it will support youtubedl-android so we don't need to create patches anymore see https://github.com/xibr/ytdlp-lazy/issues/1

The current problem is a file `yt_dlp.zip` will not be available in the [yt-dlp releases pages](https://github.com/yt-dlp/yt-dlp/releases) so I'm planning to replace it with the `yt-dlp binary` without unzip it and set `--ffmpeg-location ` I created the changes, tested them and they seem to work fine, I haven't pushed the changes yet.

@yausername @JunkFood02 @p3g4asus What do you think?

**Comment by JunkFood02** [comment]
If I understand correctly, we will get/update the binary directly from the upstream yt-dlp repo and run it directly. If changes/patches are all set, I can do some tests with Seal. The most important issue to be aware of is the upgrade and migration from the former version.

**Comment by p3g4asus** [comment]
This is indeed a very nice improvement. It will make maintaining youtubedl-android a lot easier. Was the problem related to the location of ffmpeg,atomicpasley and ffprobe locations? If I understood all correctly, now yt-dlp will take the location of ffprobe from the location of ffmpeg specified via command line. Is this correct? Anyway this change will make being up to date with yt-dlp versions a lot easier.

**Comment by xibr** [comment]
> we will fetch/update the binary from the upstream yt-dlp repo and run it with python3

Yes that's right.

> If changes/patches are all set, I can do some tests with Seal.

[pukkandan](https://github.com/pukkandan) has merged the changes https://github.com/yt-dlp/yt-dlp/commit/8420a4d06370d4a3db0f068f5fc9520406d33c40, also i built a yt-dlp binary file with those changes.



> The most important issue to be aware of is the upgrade and migration from the former version.

When I tested it I haven't found any problem yet.



> Was the problem related to the location of ffmpeg,atomicpasley and ffprobe locations?

If ffmpeg location is set then `libffprobe.bin.so` is not found but with  https://github.com/yt-dlp/yt-dlp/commit/8420a4d06370d4a3db0f068f5fc9520406d33c40 the problem is solved.



> If I understood all correctly, now yt-dlp will take the location of ffprobe from the location of ffmpeg specified via command line. Is this correct?

Yes that's right.

**Comment by xibr** [comment]
Also, we will not merge #176  until after the next version of yt-dlp so that there will be no problem, We will keep [ytdlp-lazy](https://github.com/xibr/ytdlp-lazy) to support previous versions of [youtubedl-android](https://github.com/yausername/youtubedl-android).

**Comment by JunkFood02** [comment]
I'll test it with Seal later to see whether everything works well

**Comment by xibr** [comment]
I also tested on API 29, 28 and 21 and didn't find any problem.

**Comment by xibr** [comment]
#176 merged.
