### ISSUE TITLE
Add aria2c as external downloader

### ISSUE THREAD

**Issue by JunkFood02** [yausername/youtubedl-android#177]
- See https://github.com/JunkFood02/Seal/issues/148

**Comment by xibr** [comment]
In my opinion let's give it more testing, and see the issues that need to be solved, I also noticed that there is a problem with the text progress bar sometimes it is not updated.

I'll create a pull request maybe tomorrow until we test it well then let's decide what we're going to do.

**Comment by xibr** [comment]
It works fine but we have a problem with the text progress bar.

**Comment by JunkFood02** [comment]
> It works fine but we have a problem with the text progress bar.

[Reference](https://aria2.github.io/manual/en/html/aria2c.html?highlight=progress#console-readout)

I'll be looking into it

**Comment by JunkFood02** [comment]
After some testing. The console output of aria2c could be parsed by the regex below:
`\[#\w{6}.*\((\d*\.*\d+)%\).*ETA:((\d+)m)*(\d+)s]`

The result would be `matcher.group(1)`, `matcher.group(3)` (nullable), `matcher.group(4)`

Test input:
```
"[#2089b0 400.0KiB/33.2MiB(1.2%) CN:1 DL:115.7KiB ETA:1m51s]",
"[#2089b0 400.0KiB/33.2MiB(100.0%) CN:1 DL:115.7KiB ETA:51s]",
"[#2089b0 400.0KiB/33.2MiB(0%) CN:1 DL:115.7KiB ETA:51s]",
"[#2089b0 400.0KiB/33.2MiB(12.3%) CN:1 DL:115.7KiB ETA:00s]"
```
Test output:
```
1.2 1 51
100.0 null 51
0 null 51
12.3 null 00
```

**Comment by JunkFood02** [comment]
After doing some tests with the library, it turns out that the yt-dlp process will be blocked by the aria2c process when downloading, along with the stdout stream. As a result, we cannot directly read the output of the aria2c from the stdout of yt-dlp.

**Comment by xibr** [comment]
After several attempts `--summary-interval=1` seems to solve the problem, please check.

**Comment by xibr** [comment]
> After doing some tests with the library, it turns out that the yt-dlp process will be blocked by the aria2c process when downloading, along with the stdout stream. As a result, we cannot directly read the output of the aria2c from the stdout of yt-dlp.

At first this is what i thought but i ran aria2c directly to test it without yt-dlp but there was a problem the progress bar is not showing.

**Comment by JunkFood02** [comment]
It works like a charm 😉
<details>
<summary>Screenshot</summary>


![image](https://user-images.githubusercontent.com/69683722/187010686-05687ff4-acd1-448d-862d-5aad6649fde2.png)

</details>

**Comment by xibr** [comment]
If there is no problem while testing this, we will need to add this patch for yt-dlp to make it work on youtubedl-android or if there is a better idea to use `libaria2c.so` 

from https://github.com/JunkFood02/Seal/issues/148#issuecomment-1224440508

```diff
diff --git a/yt_dlp/downloader/external.py b/yt_dlp/downloader/external.py
index 9859a7b33..635a8d867 100644
--- a/yt_dlp/downloader/external.py
+++ b/yt_dlp/downloader/external.py
@@ -239,7 +239,7 @@ def _make_cmd(self, tmpfilename, info_dict):
         return cmd


-class Aria2cFD(ExternalFD):
+class Libaria2cFD(ExternalFD):
     AVAILABLE_OPT = '-v'
     SUPPORTED_PROTOCOLS = ('http', 'https', 'ftp', 'ftps', 'dash_frag_urls', 'm3u8_frag_urls')
```

This is how we will use it
 https://github.com/yausername/youtubedl-android/blob/fc70f3a1120a52e0b8094139257545fc7e241c2b/app/src/main/java/com/yausername/youtubedl_android_example/DownloadingExampleActivity.java#L131-L132

**Comment by pukkandan** [comment]
About the progress bar - we have plans to parse the progress in yt-dlp itself https://github.com/yt-dlp/yt-dlp/pull/3724. However, I can't give an ETA on this

**Comment by JunkFood02** [comment]
> problem with No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/'] for now this problem can be solved by replacing /data/data/com.termux/files/usr/tmp with /storage/emulated/0/tmp in the tempfile.py in [libpython.zip.so](https://github.com/yausername/youtubedl-android/blob/master/library/src/main/jniLibs/arm64-v8a/libpython.zip.so) (May not work on Android 11+ version).


Please take a look [here](https://github.com/yausername/youtubedl-android/blob/master/library/src/main/java/com/yausername/youtubedl_android/YoutubeDL.java#L193). It seems like we disabled the "cache"(or temp?) directory by default. Could you please try enabling this and pass the directory `Environment.getExternalStorageDirectory()` to it?

**Comment by pukkandan** [comment]
>  File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 372, in _call_process
>    with TemporaryFile() as so, TemporaryFile() as se, \

The issue is coming from Python's `tempfile` module, nothing to do with `--cache-dir`. Does android have no temporary directory? Adding a `dir` to the `TemporaryFile` invocations should work around it

cc @lesmiscore

**Comment by JunkFood02** [comment]
> The issue is coming from Python's `tempfile` module, nothing to do with `--cache-dir`. Does android have no temporary directory? Adding a `dir` to the `TemporaryFile` invocations should work around it

Yes, Android doesn't have a system scope temporary file directory. And from Android 11+ on, the application can only access the file/directory within the application data directory or some limited shared directories.

**Comment by Lesmiscore** [comment]
These `TemporaryFile()` are for capturing stdout/stderr without stucking Python interpreter, so it's not necessarily in temporary directory (although shouldn't be persisted)
They can be converted to normal `open()` calls pointing to files inside `Environment.getExternalStorageDirectory()` and `os.remove` to do the same

**Comment by JunkFood02** [comment]
Aria2c and the progress text parsing looks well 👍

<details>
<summary>Screenshot</summary>

![Screenshot_20220902-014049](https://user-images.githubusercontent.com/69683722/187978656-1e33af25-bb3d-4c1c-9d13-c9abe7360feb.png)

</details>
