### ISSUE TITLE
youtube-dl latest version is not correct

### ISSUE THREAD

**Issue by poptong** [yausername/youtubedl-android#18]
https://github.com/ytdl-org/youtube-dl ----> release 2019.07.16

my youtubedel-android youtube-dl version 2019.07.14

YoutubeDL.getInstance().updateYoutubeDL(getApplication()) -> already up to date

It looks like your version of youtube-dl is outdated.
https://github.com/ytdl-org/youtube-dl Is there a way to keep it up to date?

**Comment by yausername** [comment]
It can take up to 24 hours for a [youtube-dl](https://github.com/ytdl-org/youtube-dl) release to reflect in [youtubedl-lazy](https://github.com/yausername/youtubedl-lazy).
Release 2019.07.16 is available now.
