### ISSUE TITLE
Update the FFmpeg build to the latest version

### ISSUE THREAD

**Issue by JunkFood02** [yausername/youtubedl-android#183]
I'm attempting to update the FFmpeg build version to v5.1.

According to [the termux community](https://github.com/termux/termux-app/wiki/Termux-on-android-5-or-6), the support of API 23- is ended as well as the package updates. The issue below suggests that the outdated FFmpeg build has already caused the discontinuity with the yt-dlp. 
- https://github.com/JunkFood02/Seal/issues/163

**Comment by JunkFood02** [comment]
Reference: [termux build shell script](https://github.com/termux/termux-packages/blob/master/packages/ffmpeg/build.sh)

```shell
dependencies=(ffmpeg freetype game-music-emu libaom libandroid-glob libass libbluray libbz2 libdav1d libgnutls libiconv liblzma libmp3lame libopus librav1e libsoxr libtheora libvorbis libvpx libvidstab libwebp libx264 libx265 libxml2 xvidcore zlib)
for string in ${dependencies[@]}
do
    for file in *"$string"*.deb; do
        printf '%s\n' "$file"
        dpkg-deb -xv "$file" .;
    done
done
```

**Comment by xibr** [comment]
Updating ffmpeg means giving up support for Android 5 and 6 and also it will increase app size, as you can see [here](https://github.com/yausername/youtubedl-android/blob/master/BUILD_PYTHON.md). 
> I have found the following packages to be sufficient for youtube-dl to work.

Maybe the same with ffmpeg!

Maybe in another branch.

**Comment by JunkFood02** [comment]
> Updating ffmpeg means giving up support for Android 5 and 6 and also it will increase app size, as you can see here.

Yes, I found the size of the `libffmpeg.zip.so` increase to around 30MB after building the FFmpeg on my own. Still not clear about how can we optimize this

**Comment by xibr** [comment]
> Yes, I found the size of the `libffmpeg.zip.so` increase to around 30MB after building the FFmpeg and remove many abundant .so libraries on my own. Still not clear about how can we optimize this

I will take a look and see what I can do.

from [yt-dlp readme](https://github.com/yt-dlp/yt-dlp#strongly-recommended)

> Note: There are some regressions in newer ffmpeg versions that causes various issues when used alongside yt-dlp. Since ffmpeg is such an important dependency, we provide [custom builds](https://github.com/yt-dlp/FFmpeg-Builds#ffmpeg-static-auto-builds) with patches for these issues at [yt-dlp/FFmpeg-Builds](https://github.com/yt-dlp/FFmpeg-Builds). See [the readme](https://github.com/yt-dlp/FFmpeg-Builds#patches-applied) for details on the specific issues solved by these builds

Is the error related to this?

**Comment by JunkFood02** [comment]
> Is the error related to this?

I don't think so. According to the readme, most of the patches were merged into the FFmpeg v5.1.

Maybe the different versions of the FFmpeg binaries can be packaged and released in different repos/libraries since we make little changes to them.

**Comment by xibr** [comment]
Ok, I updated ffmpeg from 4.2.1 to 5.1 so far it works fine, tested on Android 5 and 9, Please check if it works fine with 
- https://github.com/JunkFood02/Seal/issues/163

```gradle
implementation 'com.github.xibr.youtubedl-android:library:eacd0074af'
implementation 'com.github.xibr.youtubedl-android:ffmpeg:eacd0074af'
```

[xibr:update-ffmpeg](https://github.com/xibr/youtubedl-android/tree/update-ffmpeg)

**Comment by JunkFood02** [comment]
It works like a charm!

<details>

![Screenshot_20220907-155742](https://user-images.githubusercontent.com/69683722/188823017-3a4bda40-c7a2-4e2d-9bee-76e1c5236975.png)

</details>

**Comment by xibr** [comment]
Let's make sure everything is working fine so it doesn't cause us any issues after merging.

There is an idea in my mind about aria2c don't know if it will work but I will give it a try, it will reduce the size of the current aria2c.
