### ISSUE TITLE
Is there a way to get video info for playlists or search queries?

### ISSUE THREAD

**Issue by deniscerri** [yausername/youtubedl-android#190]

**Comment by JunkFood02** [comment]
See https://github.com/JunkFood02/Seal/pull/29 for a [workaround](https://github.com/JunkFood02/Seal/blob/main/app/src/main/java/com/junkfood/seal/util/DownloadUtil.kt#L79). More specifically, use `-I` to obtain info of items in playlists. I haven't used searching in yt-dlp but you may parse the response in a similar way.

**Comment by deniscerri** [comment]
Thank you. I found out that for search you need to do this
`request.addOption("--default-search",  "ytsearch25");` number in the end gives you the number of results
