### ISSUE TITLE
Add support for options with multiple arguments

### ISSUE THREAD

**Issue by deniscerri** [yausername/youtubedl-android#197]
I am trying to use the command --replace-in-metadata "metadata-name" "regex" "replacement" but currently only one argument is allowed.
I tried to add quotation marks manually but it still considers everything as one argument
 `request.addOption("--replace-in-metadata", "\"title\" \"[ ]\" \""+replacement+"\"");`

**Comment by JunkFood02** [comment]
[Custom command](https://github.com/yausername/youtubedl-android/blob/master/library/src/main/java/com/yausername/youtubedl_android/YoutubeDLRequest.java#L39) would work for complicated use cases like this.

**Comment by deniscerri** [comment]
worked flawlessly. Thank you
