### ISSUE TITLE
the app can't download videos with special character titles or emojis like"Which iPad Breaks first? 😮🤯 #ipad #phones #break #bend" 

### ISSUE THREAD

**Issue by Kaleb09** [yausername/youtubedl-android#198]
I want to download some video's from twitter and YouTube and the app shows the download is finished successfully but when 
I go to the download directory it shows the file with 0 byte and even I can't delete the file
the video URL is "https://www.youtube.com/shorts/phGlO0Lt-Tk"

**Comment by JunkFood02** [comment]
This example app is not for common usage, use dvd or [Seal](https://github.com/JunkFood02/Seal) instead.
