### ISSUE TITLE
Obsolete OpenSSL version 1.1.1d

### ISSUE THREAD

**Issue by al-tush** [yausername/youtubedl-android#199]
Using youtubedl-android (including latest changes https://github.com/yausername/youtubedl-android/commit/8bc8e77349d6049649bc224b41b42c0ffe4c5294 ) causes error in Play Market Console:
```
Defective OpenSSL Version.
Your app uses a defective version of the OpenSSL library, which can cause your app to crash. 
Update to a fixed version of OpenSSL.
Defective versions: OpenSSL 1.1.1d
```

https://support.google.com/faqs/answer/12576638

**Comment by GuilhermeCouto** [comment]
Amy update for this issue???
