### ISSUE TITLE
Can't download from Pornhub

### ISSUE THREAD

**Issue by MimuraKyosuke** [yausername/youtubedl-android#203]
Always I am indebted.
It is described as follows.
Please fix if possible.

https://github.com/yt-dlp/yt-dlp/issues/4627
Workaround: use Python 3.10+

**Comment by JunkFood02** [comment]
Update to yt-dlp 2022.11.11 and see if it's fixed

**Comment by MimuraKyosuke** [comment]
Thank you for your reply.
It was fixed!
