### ISSUE TITLE
Defective OpenSSL Version

### ISSUE THREAD

**Issue by gold-devoloper** [yausername/youtubedl-android#210]
Your app uses a defective version of the OpenSSL library, which can cause your app to crash. Update to a fixed version of OpenSSL.

Defective versions:

OpenSSL 1.1.1d in lib/arm64-v8a/libpython.zip.so.UNPACKED_ARCHIVE/usr/lib/libssl.so.1.1

**Comment by milan-tejani-i2i** [comment]
any update here @gold-devoloper @yausername?

**Comment by xibr** [comment]
Please check this https://github.com/yausername/youtubedl-android/issues/220#issuecomment-1488574546
