### ISSUE TITLE
Unable to extract uploader id;

### ISSUE THREAD

**Issue by kyrellous** [yausername/youtubedl-android#216]
com.yausername.youtubedl_android.YoutubeDLException: WARNING: ffmpeg-location /data/app/~~LHwmEiXiPVswfJaVgJw2pg==/com.imagks.themaster-gr-qWQl1nWeJx4LHLSPDiQ==/lib/x86/libffmpeg.so does not exist! Continuing without ffmpeg
    WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 104] Connection reset by peer>
    WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (1/3)...
    WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (2/3)...
    WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 104] Connection reset by peer>
    ERROR: [youtube] mDqYn0XZTZw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by bigproof2010** [comment]
Hello same error here trying to play one video Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by xibr** [comment]
https://github.com/yausername/youtubedl-android/issues/214
