### ISSUE TITLE
not an issue but...

### ISSUE THREAD

**Issue by idontveapc** [yausername/youtubedl-android#219]
questions like the audio format, can be what, like **.wav** or can also be set **aiff?** Or just **_.mp3_** or **.opus** or **.ogg?** Can you get non-compressed!?

and how can you set quality for videos? how can you download captions?

devs can reply, like, in **YES!** or **no :(**

**Comment by JunkFood02** [comment]
please use [Seal](https://github.com/JunkFood02/Seal)

**Comment by idontveapc** [comment]
> please use [Seal](https://github.com/JunkFood02/Seal) 

i occassionally use it, but u get medium bitrates of either .m4a or .opus(WebM)



**am i late???** **CUZ I MOVED ON.**

**Comment by JunkFood02** [comment]
You can only download the formats provided by the platform. For YouTube, they're usually 128 kbps OPUS/M4A (256 kbps with YouTube Premium + YT Music)
Some apps convert the 128 kbps audio to 320 kbps mp3 or other "high quality" formats, but it only causes loss in audio quality and makes the files larger

**Comment by idontveapc** [comment]
> You can only download the formats provided by the platform. For YouTube, they're usually 128 kbps OPUS/M4A (256 kbps with YouTube Premium + YT Music) Some apps convert the 128 kbps audio to 320 kbps mp3 or other "high quality" formats, but it only causes loss in audio quality and makes the files larger

can you use YouTube a/c credentials in yt-dlp? some people that i found can dl in `f 141`, not sure they bought yt subscription or not.?!
