### ISSUE TITLE
Defective versions:  OpenSSL 1.1.1d in lib/arm64-v8a/libpython.zip.so.UNPACKED_ARCHIVE/usr/lib/libssl.so.1.1

### ISSUE THREAD

**Issue by syedusama5556** [yausername/youtubedl-android#220]
i tried to upload an app to play store with this library it gave this issue. i am using the latest build i used this library 

```
 implementation 'com.github.yausername.youtubedl-android:library:-SNAPSHOT'
 implementation 'com.github.yausername.youtubedl-android:ffmpeg:-SNAPSHOT'
```

```
Your app uses a defective version of the OpenSSL library, which can cause your app to crash. Update to a fixed version of OpenSSL.

Defective versions:

OpenSSL 1.1.1d in lib/arm64-v8a/libpython.zip.so.UNPACKED_ARCHIVE/usr/lib/libssl.so.1.1
```

<img width="723" alt="image" src="https://user-images.githubusercontent.com/29094408/222826643-0d5052d1-4a87-4fb9-aa1c-d8392a0c2d66.png">

**Comment by sunsoek** [comment]
Somewhat related but YouTubedl isn’t really a legal application so I wouldn’t publish your app on the Play Store.

**Comment by Kaynat148** [comment]
have your issue resolved ?

**Comment by xibr** [comment]
Please try this 
```
implementation 'com.github.yausername.youtubedl-android:library:update-openssl-SNAPSHOT'
implementation 'com.github.yausername.youtubedl-android:ffmpeg:update-openssl-SNAPSHOT
```
I have updated the OpenSSL version from `OpenSSL 1.1.1d 10 Sep 2019` to `OpenSSL 1.1.1t 7 Feb 2023`
