### ISSUE TITLE
Make this library proguard friendly

### ISSUE THREAD

**Issue by zunjae** [yausername/youtubedl-android#222]
Hello

Just wanted to thank you for developing this library.

I have a suggestion

Since I heavily obfuscate my code - including those from third party libraries - json serialization breaks. The variable `description` inside `VideoInfo` gets changed to `abcd`, causing the deserialization to fail.

A workaround I don't really agree with is using 

`-keep class com.yausername.youtubedl_android.mapper.** { *; }`

A solution to this problem is to annotate each variable in your Java class. I know this sounds like a pain, but it can be automated inside Android Studio using a json plugin.

so 

```
private String fulltitle;
```

becomes

```
@JsonProperty("fulltitle")
private String fulltitle;
```

**Comment by JunkFood02** [comment]
parse the json response by yourself is probably a better solution

**Comment by JunkFood02** [comment]
Also, this library can be only used under the GPLv3 license. In other words, you're prohibited to use this library when you're using it in your closed source software

**Comment by zunjae** [comment]
Good to know. In that case I'll have to drop this library.
