### ISSUE TITLE
Response getOut();

### ISSUE THREAD

**Issue by bunaif** [yausername/youtubedl-android#23]
hi, I have problem with Encoding in 
`youtubeDLResponse.getOut();` 

![Screenshot_youtube dl](https://user-images.githubusercontent.com/20098154/66734395-fcb6d100-ee73-11e9-9e10-bd59a09d076f.jpg)
But in termux 
![Screenshot_Termux](https://user-images.githubusercontent.com/20098154/66734439-23750780-ee74-11e9-863d-e788b3ee8eae.jpg)
 How can I fix it
Video url [https://youtu.be/gqBryLoNYLA](https://youtu.be/gqBryLoNYLA) 
Video title 

> 【山药村老板娘】秋天到了，隔壁大婶家南瓜熟了，摘一个焖3斤排骨，真香

Thanks.

**Comment by yausername** [comment]
@bunaif I have fixed the issue in version 0.6.2. Please test and confirm.
Thanks

**Comment by bunaif** [comment]
Hello, the problem has been fixed
Now it's work fine
 Thanks.

![Screenshot_youtube dl](https://user-images.githubusercontent.com/20098154/66778811-cdd54500-eedd-11e9-8352-0b6001506d5b.jpg)
