### ISSUE TITLE
[Question] Is there anyway that Python can be updated?

### ISSUE THREAD

**Issue by BobbyESP** [yausername/youtubedl-android#230]
Hi! Hope you are all good. I wanted to know if there is anyway to update Python. I've tried many times doing what is in the docs for extracting Python from the termux-packages repo but I think that I just suck using Docker or something like that xD. Thank you!

**Comment by xibr** [comment]
You may be able to build it manually by downloading the deb files from this link
https://packages.termux.dev/apt/termux-main/pool/main/
The files you will need are in the documentation, however Android 5 and 6 will not be supported.

**Comment by BobbyESP** [comment]
Okay! Thank you for the quick response :))

**Comment by BobbyESP** [comment]
Is possible that the libutil lib isn't present anymore?

**Comment by BobbyESP** [comment]
Nevermind, I've found it in the API 21 pool

**Comment by xibr** [comment]
About your comment in https://github.com/yausername/youtubedl-android/issues/196#issuecomment-1676449198 How did you build the Python for API 21?

**Comment by BobbyESP** [comment]
> About your comment in https://github.com/yausername/youtubedl-android/issues/196#issuecomment-1676449198 How did you build the Python for API 21? 

I downloaded the packages that you mention in there that are the needed debs, used the zip command that I don't remember right now and that created the zip.

**Comment by BobbyESP** [comment]
I have made this MD document for myself in a future.
[SPOTDL-ANDROID - The docs.md](https://github.com/yausername/youtubedl-android/files/12342246/SPOTDL-ANDROID.-.The.docs.md)
