### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by the12devil** [yausername/youtubedl-android#239]
im using 'com.github.yausername.youtubedl-android:library:4f00394' and when im trying to download a song using android studio im getting this error : 
com.yausername.youtubedl_android.YoutubeDLException: WARNING: ffmpeg-location /data/app/~~99hd00nLMELip8EX6KFKqQ==/com.example.musica-ZYsAMrxlXk-1evrSyNpQMg==/lib/x86/libffmpeg.so does not exist! Continuing without ffmpeg

ERROR: [youtube] KtGFByAJRQQ: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

i used the snapshot and switch to the 4f00394 version because the snapshot did problems

**Comment by JunkFood02** [comment]
Update yt-dlp
