### ISSUE TITLE
Failed to resolve: com.github.yausername.youtubedl-android:ffmpeg:-SNAPSHOT

### ISSUE THREAD

**Issue by HasanAnorov** [yausername/youtubedl-android#240]
I am using these dependencies as stated on installation of library
    //YT downloader library
    implementation 'com.github.yausername.youtubedl-android:library:-SNAPSHOT'
    implementation 'com.github.yausername.youtubedl-android:ffmpeg:-SNAPSHOT' // Optional
    implementation 'com.github.yausername.youtubedl-android:aria2c:-SNAPSHOT' // Optional
    
 but getting these errors:
 Failed to resolve: com.github.yausername.youtubedl-android:ffmpeg:-SNAPSHOT

**Comment by cjy2103** [comment]
change it like this

implementation 'com.github.yausername.youtubedl-android:library:42c7dfcee1'
implementation 'com.github.yausername.youtubedl-android:ffmpeg:42c7dfcee1'

**Comment by HasanAnorov** [comment]
Yess it is working but why this is not mentioned in the library docs, and above library contains the same methods with different parameters, should I update my whole old codebase

**Comment by cjy2103** [comment]
Well... First of all, this is a temporary measure by the developers.

This is not officially recommended.

That's why the docs don't seem to mention that method.

To give you one more piece of information, when it is built in this way and then changed again as shown in the official document below

    implementation 'com.github.yausername.youtubedl-android:library:0.14.+'
    implementation 'com.github.yausername.youtubedl-android:ffmpeg:0.14.+' // optional
    implementation 'com.github.yausername.youtubedl-android:aria2c:0.14.+' // optional

or

    implementation 'com.github.yausername.youtubedl-android:library:-SNAPSHOT'
    implementation 'com.github.yausername.youtubedl-android:ffmpeg:-SNAPSHOT' // optional
    implementation 'com.github.yausername.youtubedl-android:aria2c:-SNAPSHOT' // optional

Sometimes it builds normally.

**Comment by HasanAnorov** [comment]
ok understood, thanks

**Comment by cjy2103** [comment]
More information

In some cases, changing the JDK vendor may cause it to build normally.

**Comment by NewMacPro** [comment]
> 

where I can see the latest version ,just like "42c7dfcee1"?
thanks

**Comment by cjy2103** [comment]
This was mentioned by "xibr" in issue #180.

**Comment by BobbyESP** [comment]
In summary, Jitpack sucks but it's the only platform for uploading GitHub libraries without paying.

**Comment by Shahboz79** [comment]
Dude did you solve this

**Comment by JunkFood02** [comment]
use `e6e89c8395` instead
