### ISSUE TITLE
Resolve Duplicate FFmpeg Code between arthenica/ffmpeg-kit and youtubedl-android

### ISSUE THREAD

**Issue by matsumo0922** [yausername/youtubedl-android#246]
I have installed `arthenica/ffmpeg-kit` to run FFmpeg in my app.

However, since `youtubedl-android` also needs ffmpeg, there are two native ffmpeg codes in the app, and the app size is very large.

Is there any way to run ffmpeg in `youtubedl-android` to solve this problem?

**Comment by JunkFood02** [comment]
https://github.com/yausername/youtubedl-android/blob/master/library/src/main/java/com/yausername/youtubedl_android/YoutubeDL.kt#L154C1-L154C9

This library runs ffmpeg binary executable directly in shell and might not fit your use case

**Comment by matsumo0922** [comment]
I see...
I would like to look for another approach.
