### ISSUE TITLE
Update FFmpeg to the lastet version

### ISSUE THREAD

**Issue by JunkFood02** [yausername/youtubedl-android#258]
The last ffmpeg update was a year ago(#183), and the previous version (v5.1) of ffmpeg already had some incompatibilities with yt-dlp:
- https://github.com/JunkFood02/Seal/issues/1099
- https://github.com/JunkFood02/Seal/issues/1173
- https://github.com/JunkFood02/Seal/issues/1035

Update to a more recent version (v6.1 by the time writing) could maybe resolve these issues

**Comment by fillwithjoy1** [comment]
How long can we expect this update to come

**Comment by zaednasr** [comment]
@JunkFood02 is it possible to add ffmpeg progress regex?

**Comment by xibr** [comment]
- #272

**Comment by fillwithjoy1** [comment]
> @JunkFood02 is it possible to add ffmpeg progress regex?

I believe that is already done

**Comment by zaednasr** [comment]
> > @JunkFood02 is it possible to add ffmpeg progress regex?
> 
> I believe that is already done

Nope. It only grabs the ytdlp and aria2c progress

**Comment by fillwithjoy1** [comment]
> > > @JunkFood02 is it possible to add ffmpeg progress regex?
> > 
> > 
> > I believe that is already done
> 
> Nope. It only grabs the ytdlp and aria2c progress

oh I realize where ffmpeg is used, my bad

**Comment by BobbyESP** [comment]
#272 Closed this issue
