### ISSUE TITLE
error=13, Permission denied

### ISSUE THREAD

**Issue by nowfalsalahudeen** [yausername/youtubedl-android#26]
Caused by: java.io.IOException: Cannot run program "/data/user/0/com.yausername.youtubedl_android_example/files/youtubedl-android/packages/usr/bin/python": error=13, Permission denied

tested both emulator and real device( android 10 ,s10)

**Comment by yausername** [comment]
Hi,
This seems to be related to the specific issue ["Android Q blocks executing binaries in your apps private data directory"](https://www.reddit.com/r/androiddev/comments/b2inbu/psa_android_q_blocks_executing_binaries_in_your/).
I will look into how this can be fixed.
Thanks for reporting.

**Comment by nowfalsalahudeen** [comment]
> Hi,
> This seems to be related to the specific issue ["Android Q blocks executing binaries in your apps private data directory"](https://www.reddit.com/r/androiddev/comments/b2inbu/psa_android_q_blocks_executing_binaries_in_your/).
> I will look into how this can be fixed.
> Thanks for reporting.

Thanks for the reply..try to fix it if u can..am also doing some research about it.if i a found a properway.i will inform u

**Comment by nowfalsalahudeen** [comment]
any updates ?

**Comment by yausername** [comment]
Sorry, not anything yet.

**Comment by uditkarode** [comment]
"While exec() no longer works on files within the application home directory, it continues to be supported for files within the read-only /data/app directory. In particular, it should be possible to package the binaries into your application's native libs directory and enable android:extractNativeLibs=true, and then call exec() on the /data/app artifacts. A similar approach is done with the wrap.sh functionality, documented at https://developer.android.com/ndk/guides/wrap-script#packaging_wrapsh."

might help :)

**Comment by rcaselles** [comment]
Any updates?

**Comment by nowfalsalahudeen** [comment]
> Any updates?
exec() no longer works on files within the application home directory
new android policy denied it

**Comment by yausername** [comment]
Hi,
I have tried to fix this in #43 
Test and let me know if it works.
Thanks

**Comment by jungyoungsoo** [comment]
I have same problem... 
youtube-dl 2020.05.03 <-- not fixed. 
api level 23 version 
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced
libandroid-support.so

**Comment by yausername** [comment]
@jungyoungsoo you can try with the latest release `0.8.0` although I am not sure if it will work with android 6.0.

**Comment by jungyoungsoo** [comment]
it's 0.8.0.
not working api level devices < 24
it show error log
Logger.e(e, "failed to download");
com.yausername.youtubedl_android.YoutubeDLException: WARNING: linker: /data/app/com.yausername.youtubedl_android_example-2/lib/arm/libpython.bin.so: unused DT entry: type 0x1d arg 0xae
CANNOT LINK EXECUTABLE: library "libpython3.8.so.1.0" not found
page record for 0xb6eef00c was not found (block_size=16)

**Comment by yausername** [comment]
@jungyoungsoo I have updated the apks in https://github.com/yausername/youtubedl-android/issues/44 
Please test and post any problems on that issue. Don't post on this issue since this is unrelated.

**Comment by yausername** [comment]
Fixed in `0.8.0` or later.
