### ISSUE TITLE
( lib/x86_64/libpython.zip.so) Malware, Mobile Unwanted Software & Behavior Transparency in google playstore

### ISSUE THREAD

**Issue by syedusama5556** [yausername/youtubedl-android#260]
Google has suspended the app for being a virus due to using this library can you kindly update this library to the latest version so that we can appeal to Google to reinitiate the application I have also attached a virus total virus checklink and a screenshot which is clearly flagging the LibPython Library as a virus so kindly check it out and resolve the issue as soon as possible if you can

### Virustotal link: 

[https://www.virustotal.com/gui/file/251c239695bb456192340e76ee0bb84f424bcd5177ec6ad10118462293ab131e/relations](url)

### Virustotal screenshot:

![www virustotal com_gui_file_251c239695bb456192340e76ee0bb84f424bcd5177ec6ad10118462293ab131e_relations](https://github.com/yausername/youtubedl-android/assets/29094408/c3b1c27a-5bd9-45b9-91ca-45b3eb4533d3)

### Google suspension email:

<img width="726" alt="image" src="https://github.com/yausername/youtubedl-android/assets/29094408/fa9c019e-f541-41e6-a404-668a3a3c23f6">

**Comment by JunkFood02** [comment]
Hi, this library is licensed under [GPL-3.0](https://github.com/yausername/youtubedl-android?tab=GPL-3.0-1-ov-file#readme), which requires any apps using this library should have their source codes open, and distributed under a [GPL-compatible license](https://www.gnu.org/licenses/license-list.html). And it seems that the source codes for your app "Video Downloader Pro" is not available under your GitHub profile. 

> kindly check it out and resolve the **license** issue as soon as possible if you can

**Comment by JunkFood02** [comment]
Hi @syedusama5556 I'm still waiting for your reply here. Please get back to me as soon as possible!

**Comment by JunkFood02** [comment]
I can't see any changes other than my commits in [syedusama5556/Seal_downloader_yt-dlp_kotlin](https://github.com/syedusama5556/Seal_downloader_yt-dlp_kotlin), and I believe this is not the source code of your so-called video downloader app.

**Comment by JunkFood02** [comment]
No, **this is the issue**. If you do not comply with the open source license when using open source code, then you have infringed the copyright of us, in other words, you have violated copyright law

**Comment by JunkFood02** [comment]
simply don't include x86_64 libs when building the app if you suspect it's the cause of this issue

**Comment by tomleejumah** [comment]
> if you suspect it's the cause of this issue

error 404 lol
