### ISSUE TITLE
How to stop downloading?

### ISSUE THREAD

**Issue by poptong** [yausername/youtubedl-android#27]
compositeDisposable.clear();
compositeDisposable.dispose();

it is not stop..

**Comment by yausername** [comment]
There is no option to do that at the moment. I will add in a future release, hopefully soon.

**Comment by poptong** [comment]
Do you have any ideas to stop?
Can't wait for the next release.

> 현재로서는 그렇게 할 수있는 옵션이 없습니다. 향후 릴리스에 추가 할 예정입니다.

**Comment by yausername** [comment]
Hey @poptong ,
I released `0.7.0` which will stop downloading when you call  `compositeDisposable.dispose();`
Rx might throw `InterruptedException` for which you need to set global Rx error handler like [here](https://github.com/yausername/youtubedl-android/blob/dd2c941417fe8a46176169adbb2603d363d74440/app/src/main/java/com/yausername/youtubedl_android_example/App.java#L30).
