### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by JunkFood02** [yausername/youtubedl-android#274]
After #272, we're hitting `Git error. Max repo size 500MB exceeded` on JitPack that prevents us from building and publishing new artifacts/releases.

There have already been reports about JitPack's unreliability. Given this issue, it might be a good opportunity to switch to a more dependable platform to host and publish our library.

**Comment by BobbyESP** [comment]
Sonatype (Maven Central) seems to be a good option. In there I have [a library](https://central.sonatype.com/artifact/io.github.bobbyesp.lyricfier/lyricfier) and works just nice. The problem is that I'm not sure about the max. repo size

**Comment by JunkFood02** [comment]
https://central.sonatype.com/namespace/io.github.junkfood02.youtubedl-android
