### ISSUE TITLE
README references the wrong repo?

### ISSUE THREAD

**Issue by sjmik** [yausername/youtubedl-android#301]
Looks like this commit clobbered the README:
https://github.com/yausername/youtubedl-android/commit/7d661d910d74e6eeecf99e199ba6da3b85881c21

![image](https://github.com/user-attachments/assets/85731f03-bed3-410b-8019-dd81fe62de2d)

Or, if that was intentional, can you explain why?

**Comment by JunkFood02** [comment]
#274

**Comment by sjmik** [comment]
Ohh, I see.  Thanks!
