### ISSUE TITLE
how to build ffmpeg

### ISSUE THREAD

**Issue by tinybug** [yausername/youtubedl-android#34]
hi~ @yausername could you tell me how to build ffmpeg? The ffmpeg you build encode mp3 faster than I build. I want to remove some encoder to make ffmpeg smaller. Thanks~

**Comment by yausername** [comment]
Build instructions are available [here](https://github.com/yausername/youtubedl-android/blob/master/BUILD_FFMPEG.md)

**Comment by tinybug** [comment]
It helps a lot. Many thanks.
