### ISSUE TITLE
ERROR ON URL FROM PLAYLIST

### ISSUE THREAD

**Issue by gbrlfrc** [yausername/youtubedl-android#36]
hey :)
I tried to downlaod video from a playlist but the downlaoder failed; I notice that this error occurred for every link of video that appear on a youtube playlist

**Comment by yausername** [comment]
Hi,
Sorry for the late reply.
Can you share a link for which the download fails?

**Comment by gbrlfrc** [comment]
Dont worry, this is one on which it fails:

https://youtu.be/Z_UOmAed5O8

I think  you can try with one random video in a playlist. 
Thanks for the answer.

**Comment by yausername** [comment]
It works with the latest release `0.9.0`. You can reopen if it still doesn't work for you.
