### ISSUE TITLE
mp3 download

### ISSUE THREAD

**Issue by jungyoungsoo** [yausername/youtubedl-android#37]
YoutubeDLRequest request
request.setOption("-x", "--extract-audio");
it's download success but format is not mp3.
I try 
request.setOption("-x", "--extract-audio --audio-format mp3) and
request.setOption("-x", "--extract-audio --audio-format mp3 " + url)
but all fialed 
failed error message show no have option ' --audio-format'

**Comment by yausername** [comment]
Can you try in the below format?
```java
String url = "https://www.youtube.com/watch?v=7tO_eJek6D8"
String youtubeDLDir = String.valueOf(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS));
YoutubeDLRequest request = new YoutubeDLRequest(url);

request.setOption("-o", youtubeDLDir + "/%(title)s.%(ext)s" );
request.setOption("--extract-audio");
request.setOption("--audio-format", "mp3");
```

**Comment by jungyoungsoo** [comment]
it's working~ great! thank you so much
