### ISSUE TITLE
Download Video range

### ISSUE THREAD

**Issue by linkkader** [yausername/youtubedl-android#39]
Hi 
I want download video range ? To download starting from 1m 30 to 1m 50?
I found this 

> ffmpeg` -ss 14350 -i $(youtube-dl -f 22 --get-url https://www.youtube.com/watch?v=mMZriSvaVP8) -t 11200 -c:v copy -c:a copy `react-spot.mp4`

here https://github.com/ytdl-org/youtube-dl/issues/622#issuecomment-162337869
but i but I can't use it in android studio . thanks`

**Comment by xibr** [comment]
it's need ffmpeg commands but this library doesn't support ffmpeg commands for now.
