### ISSUE TITLE
Unable to get the library working

### ISSUE THREAD

**Issue by shkcodes** [yausername/youtubedl-android#4]
Logs
`E/PRETTY_LOGGER: │ failed to get stream info : com.yausername.youtubedl_android.YoutubeDLException: /data/user/0/com.yausername.youtubedl_android_example/files/youtubedl-android/python/usr/bin/python[1]: syntax error: unexpected '@4L4'
`

This is from the sample app. I get a similar error when I try out the library in my own project. I tried multiple Youtube urls.

Let me know if you need any more info.

**Comment by yausername** [comment]
I am not sure what is wrong here.

1. Can you tell which device are you running this on?
2. Does this happen in both streaming example and downloading example?
3. Are you using the latest version/code?
4. Can you share an example url which fails?

**Comment by shkcodes** [comment]
1) I am using a Macbook Pro and an emulator (api 28).
2) Yes.
3) Yes.
4) https://www.youtube.com/watch?v=e-ORhEE9VVg

I am guessing this is an error related to python.

**Comment by yausername** [comment]
Can you try to test on a real device. I am suspecting the problem might be because of the emulator.

**Comment by yausername** [comment]
If you don't have a device then select an arm image instead of x86 when creating emulator as explained [here](https://stackoverflow.com/a/46677457/3663254)

**Comment by shkcodes** [comment]
Got it thanks! Though you might want to mention this in the readme.

**Comment by yausername** [comment]
Sure, cheers!
