### ISSUE TITLE
Failed to initialize youtubedl-android on x86

### ISSUE THREAD

**Issue by qiuzhihui** [yausername/youtubedl-android#42]
Getting exception on LINK EXECUTABLE.
```
failed to initialize youtubedl-android
    com.yausername.youtubedl_android.YoutubeDLException: CANNOT LINK EXECUTABLE "/system/bin/ndk_translation_program_runner_binfmt_misc": 

"/data/user/0/com.makeworldbetter/files/youtubedl-android/packages/usr/lib/libcrypto.so" 

is for EM_ARM (40) instead of EM_386 (3)
```

I found the issue is related to my build is x86 instead of arm which due to the python setup architecture here: https://github.com/yausername/youtubedl-android/blob/master/BUILD_PYTHON.md. 

Wondering if you have plan to support for x86?

**Comment by yausername** [comment]
> Wondering if you have plan to support for x86?

It is in the works. You can try it out at #43
