### ISSUE TITLE
TikTok videos not getting file extension

### ISSUE THREAD

**Issue by CoreyVidal** [yausername/youtubedl-android#45]
(First of all: I love this app. Having youtube-dl on my phone is so amazing.)

So TikTok lets you download some videos—but not others—in-app. So on videos that don't have a download button, I clicked Copy Link, and pasted the link to download in youtubedl-android.

I lagged at 0% for a moment, then jumped to 100%.

However, when I looked at the youtubedl-android folder in my Downloads folder, the file was there, but with the wrong extension.

Listed filename:
Ediz & Ben on TikTok.unknown_video

Should be:
Ediz & Ben on TikTok.mp4

I manually renamed it, and it worked perfectly.

Here's the video URL:
https://vm.tiktok.com/c6fCF7/

**Comment by yausername** [comment]
This is a youtube-dl issue. Someone has already reported it https://github.com/ytdl-org/youtube-dl/issues/23564. You can update youtube-dl when they fix the issue.
