### ISSUE TITLE
play store app upload issue

### ISSUE THREAD

**Issue by jungyoungsoo** [yausername/youtubedl-android#47]
hello sir.
i can't upload play store cos of error meesage 
google upload error message
This release version does not comply with Google Play 64-bit requirements.
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
I'm already addfilters but it's same show error message 
you konw?

**Comment by jungyoungsoo** [comment]
It cannot be uploaded.
Uploading is not possible if 64-bit is not included. This is a Google policy.
Even if I add it to my app, I can't upload it. This is because the internal library is not supported.

**Comment by yausername** [comment]
Putting this up on play store is a violation of their terms. Your app might be removed or account banned.
As for 64 bit support, you can download 64 bit binaries (including dependencies) from http://termux.net/dists/stable/main/ and extract and repack them as explained [here](https://github.com/yausername/youtubedl-android/blob/master/BUILD_PYTHON.md).

**Comment by jungyoungsoo** [comment]
> Putting this up on play store is a violation of their terms. Your app might be removed or account banned.
> As for 64 bit support, you can download 64 bit binaries (including dependencies) from http://termux.net/dists/stable/main/ and extract and repack them as explained [here](https://github.com/yausername/youtubedl-android/blob/master/BUILD_PYTHON.md).

yes I know very thank you so much

**Comment by jungyoungsoo** [comment]
> Putting this up on play store is a violation of their terms. Your app might be removed or account banned.
> As for 64 bit support, you can download 64 bit binaries (including dependencies) from http://termux.net/dists/stable/main/ and extract and repack them as explained [here](https://github.com/yausername/youtubedl-android/blob/master/BUILD_PYTHON.md).

sorry I don't understand how to apply library.
apk analyze show only armeabi-v7a and x86
I just use library from build gradle dependency
    implementation 'com.github.yausername.youtubedl-android:library:0.9.+'
    implementation 'com.github.yausername.youtubedl-android:ffmpeg:0.9.+'

can you help me?

**Comment by yausername** [comment]
You can fork this project and use the forked version instead.
Or you can add the library code as modules in your project.
To add 64 bit support you will need to add pythong and ffmpeg packages in `arm64-v8a` and `x86_64` directories. I have given hints on how to build packages above.
It should look something like this
```
./ffmpeg/src/main/jniLibs/x86_64/libffmpeg.bin.so
./ffmpeg/src/main/jniLibs/x86_64/libffmpeg.zip.so
./ffmpeg/src/main/jniLibs/x86_64/libffprobe.bin.so
./library/src/main/jniLibs/x86_64/libpython.bin.so
./library/src/main/jniLibs/x86_64/libpython.zip.so
./ffmpeg/src/main/jniLibs/arm64-v8a/libffmpeg.bin.so
./ffmpeg/src/main/jniLibs/arm64-v8a/libffmpeg.zip.so
./ffmpeg/src/main/jniLibs/arm64-v8a/libffprobe.bin.so
./library/src/main/jniLibs/arm64-v8a/libpython.bin.so
./library/src/main/jniLibs/arm64-v8a/libpython.zip.so
```

**Comment by jungyoungsoo** [comment]
The *.so files is not a *.so file built with x64. But is it okay to just create a x64 jni folder and put the same file in the x64 folder?
you can understand? sorry i don't speak english well.

**Comment by yausername** [comment]
> But is it okay to just create a x64 jni folder and put the same file in the x64 folder?

I don't think that would work. You need to make the *.so for x64.
They are not actually .so files but just zip or executable files renamed as .so files.

**Comment by yausername** [comment]
You can download the 64 bit *.so files from https://send.firefox.com/download/009d9f4207c61426/#Sx9yRCqisp3bJCrfM1y7kw

**Comment by jungyoungsoo** [comment]
oh my god thank you so much

**Comment by felipebueno** [comment]
Hey, @yausername!

I just had the same problem as @jungyoungsoo.

> You can fork this project and use the forked version instead.
> Or you can add the library code as modules in your project.

Thanks for posting the solution :smiley: 

Can you (or we) add the 64 libraries to the repository so there's no need to fork it?

**Comment by yausername** [comment]
> Can you (or we) add the 64 libraries to the repository so there's no need to fork it, please?

This will increase the size of library. There is no benefit apart from google play store compliance which anyway we aren't complying.
