### ISSUE TITLE
 java.lang.IllegalStateException error

### ISSUE THREAD

**Issue by jungyoungsoo** [yausername/youtubedl-android#48]
hello sir.
java.lang.IllegalStateException error

sure i'm already
int oncreate
YoutubeDL.getInstance().init(getApplication());
YoutubeDL.getInstance().updateYoutubeDL(getApplication());

com.yausername.youtubedl_android.YoutubeDL.assertInit (YoutubeDL.java:104) com.yausername.youtubedl_android.YoutubeDL.execute (YoutubeDL.java:131)
com.yausername.youtubedl_android.YoutubeDL.getInfo (YoutubeDL.java:114)
com.yausername.youtubedl_android.YoutubeDL.getInfo (YoutubeDL.java:109)
YoutubeDL.getInstance().getInfo(video_url);
this is call stack
sometimes it's happened 
why i don't know
help me

**Comment by jungyoungsoo** [comment]
YoutubeDLRequest request = new YoutubeDLRequest(down_url);
VideoInfo info = YoutubeDL.getInstance().getInfo(request);

it's same error
it's happened not everytime.
sometimes it's happened.
java.lang.IllegalStateException error

com.yausername.youtubedl_android.YoutubeDL.assertInit (YoutubeDL.java:104) com.yausername.youtubedl_android.YoutubeDL.execute (YoutubeDL.java:131)
com.yausername.youtubedl_android.YoutubeDL.getInfo (YoutubeDL.java:114)
com.yausername.youtubedl_android.YoutubeDL.getInfo (YoutubeDL.java:109)

**Comment by yausername** [comment]
Are you sure `YoutubeDL.getInstance().init(getApplication())` has finished before you call `YoutubeDL.getInstance().getInfo(request)`?

**Comment by jungyoungsoo** [comment]
yes has finished and call but I think only happen release mode

**Comment by jungyoungsoo** [comment]
i think that may be initialize failed

**Comment by jungyoungsoo** [comment]
it seems api target... 29

**Comment by jungyoungsoo** [comment]
it happened only aab apk it's ok  i don't know why

**Comment by jungyoungsoo** [comment]
failed to initialize youtubedl-android

**Comment by jungyoungsoo** [comment]
now working fine..

**Comment by jungyoungsoo** [comment]
YoutubeDL.getInstance().init(getApplication())  initialize failed

**Comment by jungyoungsoo** [comment]
I'm sure. release apk working but aab is not working. I definitely checked.

**Comment by yausername** [comment]
@jungyoungsoo hope the issue is resolved. Reopen if not.
