### ISSUE TITLE
any wat to use download manager, fix video name

### ISSUE THREAD

**Issue by bunaif** [yausername/youtubedl-android#5]
hi, 
how to get link? if you want download it with download manager, and if you want use custom name, when download from instagram video name (video by user) you cant download other video

**Comment by yausername** [comment]
Yes, you can use direct link to download with download manager and change file name. Here is how you get the download link - 
```java
VideoInfo info = YoutubeDL.getInstance().getInfo("https://www.instagram.com/p/BvpaB-OlVR9/");
for(VideoFormat f : info.formats){
    System.out.println(f.format + " - " + f.url);
}
```
You can use the default/best format from `info.format` or any other format from `info.formats`.

Hope it helps.
Feel free to ask if you face any issue.
Thanks

**Comment by bunaif** [comment]
I will try, thank you very much

**Comment by bunaif** [comment]
hi,  from twitter cant get mp4, like instagram

my code

                VideoInfo info = null;
                try {
                    info = YoutubeDL.getInstance().getInfo(youtubeLink);
                } catch (YoutubeDLException e) {
                    e.printStackTrace();
                }
                for(VideoFormat f : Objects.requireNonNull(info).formats){
                    if(f.ext.endsWith("mp4")){
                        System.out.println(f.format + " - " + f.url);
                       break;
                    }
                 
                }

i need best format 
thanks

**Comment by bunaif** [comment]
results like this


 # hls-320 - 320x180 - mp4 - https://video.twimg.com/ext_tw_video/769083846285549568/pu/pl/320x180/Ihh0-N5hAe-QsnaY.m3u8
 # hls-832 - 640x360 - mp4 - https://video.twimg.com/ext_tw_video/769083846285549568/pu/pl/640x360/5ALvd3khE_svZdt5.m3u8
 # hls-2176 - 1280x720 - mp4 - https://video.twimg.com/ext_tw_video/769083846285549568/pu/pl/1280x720/f8xF4H3kKx9XKyzG.m3u8

I need mp4 link for 1280x720 not m3u8.

**Comment by yausername** [comment]
twitter only provides m3u8 links.
You can convert that to mp4 file on `linux` using `ffmpeg`

    ffmpeg -i https://video.twimg.com/ext_tw_video/769083846285549568/pu/pl/640x360/5ALvd3khE_svZdt5.m3u8 -c copy -bsf:a aac_adtstoasc output.mp4

I have't tried it but you can use https://github.com/bravobit/FFmpeg-Android for ffmpeg on android.
Also, exoplayer can stream m3u8 links directly.

**Comment by bunaif** [comment]
Okay,
I will use your example because it gives me video files in mp4 format

Thank you so much

**Comment by yausername** [comment]
ok.
FYI, you can set the file name by changing this line
`request.setOption("-o", youtubeDLDir.getAbsolutePath() + "/whatevernameyouwant.%(ext)s");`

**Comment by bunaif** [comment]
it's work fine, thank you so much
