### ISSUE TITLE
not out put mp3 file 

### ISSUE THREAD

**Issue by jungyoungsoo** [yausername/youtubedl-android#52]
hello sir.
i'm use 
implementation 'com.github.yausername.youtubedl-android:ffmpeg:0.9.+'        
in build gradle.

request.addOption("-o", youtubeDLDir.getAbsolutePath() + "/%(title)s.%(ext)s");
        //mp3 option
        if(onlyMP3){
            request.addOption("--extract-audio");
            request.addOption("--audio-format", "mp3");
            request.addOption("--audio-quality", "0");
}
before it's working but not mp3 file output m4a file.

**Comment by yausername** [comment]
Can you share a link for which it doesn't work?
