### ISSUE TITLE
APK?

### ISSUE THREAD

**Issue by CoreyVidal** [yausername/youtubedl-android#58]
Hopefully this is a minor request, but would you be so kind as to make an .apk for the latest release?

I'm not a developer, just someone who's desperate to have a fully working and easy to use youtube-dl on my phone. I have no idea how to compile anything. 😅

**Comment by yausername** [comment]
Yes, will update apk soon.

**Comment by yausername** [comment]
APKs updated, but I would recommend using the [dvd](https://github.com/yausername/dvd) app.
