### ISSUE TITLE
APK test request

### ISSUE THREAD

**Issue by yausername** [yausername/youtubedl-android#59]
Hi all,
I plan to publish https://github.com/yausername/dvd on fdroid.
I need help with testing.
Please find the apks on https://github.com/yausername/dvd/releases
Report any issues here. 
Thanks
@jungyoungsoo @CoreyVidal @xibr

**Comment by xibr** [comment]
hi @yausername, 

 In Android 10 cannot download, you can watch screen recording.

[Screen_Recording_20200613-105109.mp4.zip](https://github.com/yausername/youtubedl-android/files/4774215/Screen_Recording_20200613-105109.mp4.zip)

testing on Samsung Galaxy s9 plus android 10.

also on Xiaomi redmi note 7 android 9 

The same problem and could not choose the download folder.

**Comment by xibr** [comment]
I think the problem is in the downloads path or in choosing the downloads folder.

**Comment by yausername** [comment]
Yeah, will check.

**Comment by xibr** [comment]
Hi @yausername 

add this line 
`val dl = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString())`
in [HomeFragment.kt#L138](https://github.com/yausername/dvd/blob/8376fe81cc13fa20a0857f51517649bba6903633/app/src/main/java/com/yausername/dvd/ui/HomeFragment.kt#L138) and change `downloadDir` to `dl.toString()`
from 
`val workTag = downloadDir + "/" + vidInfo.id`
to 
`val workTag = dl.toString() + "/" + vidInfo.id`

and edit this [HomeFragment.kt#L180](https://github.com/yausername/dvd/blob/8376fe81cc13fa20a0857f51517649bba6903633/app/src/main/java/com/yausername/dvd/ui/HomeFragment.kt#L180)

``` 
override fun onOk(dialog: DownloadPathDialogFragment) {
        val vidFormatsVm =
            ViewModelProvider(activity as MainActivity).get(VidInfoViewModel::class.java)
        val path = PreferenceManager.getDefaultSharedPreferences(context)
            .getString("downloadLocation", null)
        if (path == null) {
            Toast.makeText(context, "invalid download location", Toast.LENGTH_SHORT).show()
            return
        }
        startDownload(vidFormatsVm.selectedItem, path)
    }
``` 
with 
``` 
override fun onOk(dialog: DownloadPathDialogFragment) {
        val vidFormatsVm =
            ViewModelProvider(activity as MainActivity).get(VidInfoViewModel::class.java)
        val path = PreferenceManager.getDefaultSharedPreferences(context)
            .getString("downloadLocation", null)
        //if (path == null) {
        //    Toast.makeText(context, "invalid download location", Toast.LENGTH_SHORT).show()
         //   return
       // }
         val dl = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString())
        startDownload(vidFormatsVm.selectedItem, dl.toString())
    }
``` 
It works for testing.

The problem with choosing the download folder you must check or make the downloads folder the default.

**Comment by yausername** [comment]
Hi,
I have made changes to the download directory logic. 
Please find the debug apk [here](https://send.firefox.com/download/db0932633383c4e0/#EmQv9oTvOsdNLcIfahM4Qg)
Make sure you uninstall the older version before installing this.
Thanks

**Comment by xibr** [comment]
Now it works and can download the video without any problem.

Also when clicking on the downloaded video it does not play.

Tested on Samsung S9 Plus Android 10, Xiaomi Android 9.

**Comment by xibr** [comment]
Also, in my opinion, you should add a way to share the link from the YouTube app to the DVD app so that the user does not every time copy the link and then move to the dvd app.

 this screenrecords when try open downloaded video on my Samsung device. android 10.
[Screen_Recording_20200614-083448.mp4.zip](https://github.com/yausername/youtubedl-android/files/4775861/Screen_Recording_20200614-083448.mp4.zip)

also app is crash when try opening downloaded videos on Xiaomi device. here android 9.

**Comment by yausername** [comment]
> Also, in my opinion, you should add a way to share the link from the YouTube app to the DVD app so that the user does not every time copy the link and then move to the dvd app.

added in release [0.0.3](https://github.com/yausername/dvd/releases/tag/0.0.3)

> Also when clicking on the downloaded video it does not play.
> also app is crash when try opening downloaded videos on Xiaomi device. here android 9.

fixed in release [0.0.3](https://github.com/yausername/dvd/releases/tag/0.0.3)

**Comment by xibr** [comment]
I did the test and it seems to be working fine.


Tested on Android 10.

**Comment by xibr** [comment]
I will check it on my other device if any issue is found I will report it.

**Comment by xibr** [comment]
I have tested on Android 5 and Android 9 and it works fine.

  Choosing the storage location is working properly
  And the download progress bar works
  When clicking on video or audio from the downloads list, audio and video can be played.

However, I noticed that if the storage location is not specified in the settings, you will be asked every time about the storage location when trying to download any video, is this normal?

**Comment by yausername** [comment]
> However, I noticed that if the storage location is not specified in the settings, you will be asked every time about the storage location when trying to download any video, is this normal?

Fixed in 0.0.4

**Comment by xibr** [comment]
Yeah it's fixed.

**Comment by neodada** [comment]
App working fine here. Just a request to show whether a format contains video and audio. Currently it shows bitrate and abr value which maybe 0 for some formats. Add vcodec and acodec values for these cases.

**Comment by yausername** [comment]
> Just a request to show whether a format contains video and audio.

Audio and video/video-only streams can be distinguished based on format icon. And when you download a video-only format, best-audio is merged with it.

> Add way to stop downloading. Currently if i force stop app and launch app download starts from beginning. It should resume previous download as youtube-dl supports resumable download.

Will look into this.

**Comment by xibr** [comment]
Currently available on f-droid.
