### ISSUE TITLE
Request sample apk for non programmer user

### ISSUE THREAD

**Issue by Brimont** [yausername/youtubedl-android#6]
Hi, sorry for the inconvenience, I wanted to know how to download the apk of this sample app https://github.com/yausername/youtubedl-android/blob/master/README.md#sample-app , I'm not a programmer so I don't know how to compile an app from github

**Comment by yausername** [comment]
Here is the sample apk [app-debug.apk.zip](https://github.com/yausername/youtubedl-android/files/3026604/app-debug.apk.zip)
Although this is meant mainly for programmers.
Thanks

**Comment by Brimont** [comment]
Thanks yausername for help!
