### ISSUE TITLE
ERROR: unable to create directory [Errno 13] Permission denied: '/storage/emulated/0/Download/youtubedl-android'

### ISSUE THREAD

**Issue by SDiCesare** [yausername/youtubedl-android#65]
After following the installation I tried to start a simple activity, but on startup I get this error:
`W/System.err: com.yausername.youtubedl_android.YoutubeDLException: ERROR: unable to create directory [Errno 13] Permission denied: '/storage/emulated/0/Download/youtubedl-android'
W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:196)
W/System.err:     at com.ike.net.musicroom.MainActivity$override.onCreate(MainActivity.java:31)
        at com.ike.net.musicroom.MainActivity$override.access$dispatch(Unknown Source:75)
W/System.err:     at com.ike.net.musicroom.MainActivity.onCreate(Unknown Source:15)
        at android.app.Activity.performCreate(Activity.java:7955)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
W/System.err:     at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5669)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5577)
W/System.err:     at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:62)
W/System.err:     at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5628)
W/System.err:     at android.app.ActivityThread.access$3400(ActivityThread.java:270)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2226)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)`

The Only method in my Activity:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        try {
            YoutubeDL.getInstance().init(getApplication());
        } catch (YoutubeDLException e) {
            Log.e("Music Room", "failed to initialize youtubedl-android", e);
        }
        File youtubeDLDir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "youtubedl-android");
        YoutubeDLRequest request = new YoutubeDLRequest("https://www.youtube.com/watch?v=yQKlfQsRaHk");
        request.addOption("-o", youtubeDLDir.getAbsolutePath() + "/%(title)s.%(ext)s");
        try {
            YoutubeDL.getInstance().execute(request, new DownloadProgressCallback() {
                @Override
                public void onProgressUpdate(float progress, long etaInSeconds) {
                    System.out.println(progress + "% (ETA " + etaInSeconds + " seconds)");
                }
            });
        } catch (YoutubeDLException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

I also added to my Manifest the permissions of INTERNET, ACCESS_NETWORK_STATE and WRITE_EXTERNAL_STORAGE, but the problem persist.

**Comment by yausername** [comment]
What version of android are you running on?
If it is >= Marshmallow, then you will need to request storage permission at runtime.
Check this method https://github.com/yausername/youtubedl-android/blob/9269291e842abebb6e6a457a8444db5b81959cd4/app/src/main/java/com/yausername/youtubedl_android_example/DownloadingExampleActivity.java#L153

**Comment by SDiCesare** [comment]
@yausername Ok, I'm running on Android 29.
I tried to change the activity, but I keep getting this error.

Activity:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final Button button = findViewById(R.id.button);
        try {
            YoutubeDL.getInstance().init(getApplication());
        } catch (YoutubeDLException e) {
            Log.e("Music Room", "failed to initialize youtubedl-android", e);
        }
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (!isStoragePermissionGranted()) {
                    Toast.makeText(getApplicationContext(), "Allow Permission", Toast.LENGTH_LONG).show();
                    return;
                }
                File youtubeDLDir = getDownloadLocation();
                YoutubeDLRequest request = new YoutubeDLRequest("https://www.youtube.com/watch?v=yQKlfQsRaHk");
                request.addOption("-o", youtubeDLDir.getAbsolutePath() + "/%(title)s.%(ext)s");
                try {
                    YoutubeDL.getInstance().execute(request, new DownloadProgressCallback() {
                        @Override
                        public void onProgressUpdate(float progress, long etaInSeconds) {
                            Log.d("Music Room", progress + "% (ETA " + etaInSeconds + " seconds)");
                        }
                    });
                } catch (YoutubeDLException e) {
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    private File getDownloadLocation() {
        File downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        File youtubeDLDir = new File(downloadsDir, "youtubedl-android");
        if (!youtubeDLDir.exists()) {
            youtubeDLDir.mkdir();
        }
        return youtubeDLDir;
    }

    public boolean isStoragePermissionGranted() {
        System.out.println(Build.VERSION.SDK_INT);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
                    == PackageManager.PERMISSION_GRANTED) {
                return true;
            } else {
                ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, 1);
                return false;
            }
        } else {
            return true;
        }
    }

The Error:

`W/System.err: com.yausername.youtubedl_android.YoutubeDLException: ERROR: unable to create directory [Errno 13] Permission denied: '/storage/emulated/0/Download/youtubedl-android'
W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:196)
        at com.ike.net.musicroom.MainActivity$1.onClick(MainActivity.java:47)
        at android.view.View.performClick(View.java:7870)
W/System.err:     at android.widget.TextView.performClick(TextView.java:14970)
        at android.view.View.performClickInternal(View.java:7839)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29363)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
`

**Comment by yausername** [comment]
On android 29 you will also need to add this to your Android Manifest ` android:requestLegacyExternalStorage="true"`
See https://github.com/yausername/youtubedl-android/blob/master/app/src/main/AndroidManifest.xml#L17

**Comment by SDiCesare** [comment]
@yausername Ok thanks, now the download start correctly. But now i have this problem:

`W/System.err: com.yausername.youtubedl_android.YoutubeDLException: WARNING: Requested formats are incompatible for merge and will be merged into mkv.
W/System.err: ERROR: CANNOT LINK EXECUTABLE "libffmpeg.bin.so": library "libavdevice.so" not found
W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:196)
        at com.ike.net.musicroom.MainActivity$1.onClick(MainActivity.java:47)
W/System.err:     at android.view.View.performClick(View.java:7870)
        at android.widget.TextView.performClick(TextView.java:14970)
W/System.err:     at android.view.View.performClickInternal(View.java:7839)
        at android.view.View.access$3600(View.java:886)
W/System.err:     at android.view.View$PerformClick.run(View.java:29363)
        at android.os.Handler.handleCallback(Handler.java:883)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)`

**Comment by SDiCesare** [comment]
@yausername Ok nothing, I just forgot to initialize FFmpeg in the java code

**Comment by qzRockie** [comment]
谢谢，我在你这里找到了解决问题的灵感，我的问题是 CANNOT LINK EXECUTABLE "libffmpeg.bin.so": library "libavdevice.so" not found，但是我的初始化是成功了的，但是文件夹放的不是同一个，修改了就正常了
