### ISSUE TITLE
Youtube Player

### ISSUE THREAD

**Issue by UserI33X** [yausername/youtubedl-android#66]
What do I need in my java file to play a youtube video via a link and play it in exoplayer or something. Thank u.

**Comment by yausername** [comment]
You can do something like this to get a playable link
```java
YoutubeDLRequest request = new YoutubeDLRequest(url);
request.addOption("-f", "best");
VideoInfo streamInfo = YoutubeDL.getInstance().getInfo(request);
System.out.println(streamInfo.getUrl());
```
See [this](https://github.com/yausername/youtubedl-android/blob/master/app/src/main/java/com/yausername/youtubedl_android_example/StreamingExampleActivity.java) for a comprehensive example.
