### ISSUE TITLE
-a batch file command

### ISSUE THREAD

**Issue by dropitlikecross** [yausername/youtubedl-android#68]
Hello,

Having some difficulties getting the -a command to work in the custom area:

-a, --batch-file FILE            File containing URLs to download ('-' for
                                 stdin), one URL per line. Lines starting
                                 with '#', ';' or ']' are considered as
                                 comments and ignored.

Is this normal?

**Comment by yausername** [comment]
I tried this command and it works.
```
-o /sdcard/Download/youtubedl-android/%(title)s.%(ext)s -a /sdcard/batch-file
```
Try with the latest apk from the releases page and let me know if it shows any error.

**Comment by xibr** [comment]
if the line starts with "#" or " ; " will be ignored.
