### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Danoneill432** [yausername/youtubedl-android#69]
Only 1 in around 5 videos actually download starting from yesterday. The rest return an error from the python ytdl, I think it just needs to be updated as a new version of the python downloader was released yesterday

**Comment by xibr** [comment]
update youtube-dl to latest 2020.07.28

**Comment by Danoneill432** [comment]
> 
> 
> update youtube-dl to latest version 2020.07.28

How do I do that I've been having trouble editing external android libraries

**Comment by xibr** [comment]
youtube-dl library can be updated itself by clicking on "Update youtube-dl" if you are using apk file from the  [Releases](https://github.com/yausername/youtubedl-android/releases) page.

![Screenshot_20200729-033819_youtubedl-android-example.jpg](https://user-images.githubusercontent.com/20098154/88739990-06809b00-d14d-11ea-8ade-9daa19624d23.jpg)

**Comment by xibr** [comment]
if you're using this in your project then check this example to update youtube-dl library  [MainActivity.java#L94](https://github.com/yausername/youtubedl-android/blob/master/app/src/main/java/com/yausername/youtubedl_android_example/MainActivity.java#L94)

**Comment by Danoneill432** [comment]
> if you're using this in your project then check this example to update youtube-dl library  [MainActivity.java#L94](https://github.com/yausername/youtubedl-android/blob/master/app/src/main/java/com/yausername/youtubedl_android_example/MainActivity.java#L94)

Cheers mate
