### ISSUE TITLE
ffmpeg support

### ISSUE THREAD

**Issue by filisko** [yausername/youtubedl-android#7]
Would it be very difficult to add ffmpeg support for the "convert to mp3" options of youtube-dl?

**Comment by yausername** [comment]
Should not be very difficult. It is just about bundling the ffmpeg binary with the library.

**Comment by filisko** [comment]
I would much appreciate if you could do that :smile:

**Comment by yausername** [comment]
I will eventually work on it. Sadly I can't give any timelines at the moment.
I will update here if any progress is made.
Thanks

**Comment by filisko** [comment]
Yeah, that's normal :) thanks to you!

**Comment by filisko** [comment]
I've done it now with https://github.com/bravobit/FFmpeg-Android and it works well, the interesting thing would be to use the built-in features of youtube-dl with audio extract and all this things.

**Comment by yausername** [comment]
Nice!


> the interesting thing would be to use the built-in features of youtube-dl with audio extract and all this things

Yes, that's the idea.

**Comment by filisko** [comment]
:smile: goin' to test it now

**Comment by yausername** [comment]
I hope this works for you. I might later add support for running arbitrary ffmpeg commands too.

**Comment by filisko** [comment]
@yausername just managed to use the convert to mp3 feature of youtubedl and it worked nice! great job. and yes, ffmpeg commands would be interesting I guess, but you know, now youtubedl can be used with any of its parameteres :smile:

**Comment by uditkarode** [comment]
@yausername ffmpeg is now outdated, can you please set up a CI to update it too along with youtube-dl?
