### ISSUE TITLE
so what if I want the direct link of video using -g command nothing 'll display

### ISSUE THREAD

**Issue by seisdr** [yausername/youtubedl-android#70]

**Comment by yausername** [comment]
You can do something like this
```java
YoutubeDLRequest request = new YoutubeDLRequest("https://vimeo.com/22439234");
request.addOption("-g");
YoutubeDLResponse response = YoutubeDL.getInstance().execute(request);
System.out.println(response.getOut());
```

**Comment by seisdr** [comment]
yeah but why not just to display the output of whatever the command running

**Comment by seisdr** [comment]
yes

**Comment by yausername** [comment]
I have updated the sample app to include this.
You can either build the `master` branch or download debug apks from releases page.
Let me know if something does not work.

**Comment by xibr** [comment]
I think if you want to run a direct video link from YouTube, it should be like this
`-f best -g https://youtu.be/az3eW7vIjOU`

without `-f best` return HTTP ERROR 403.

**Comment by seisdr** [comment]
oh yeah it's working thank you
