### ISSUE TITLE
Add cookie to VideoInfo

### ISSUE THREAD

**Issue by swifityG** [yausername/youtubedl-android#72]
can you please add a way to get the cookie from the VideoInfo its will help me very much, thanks

**Comment by swifityG** [comment]
did it myself with jsonObject.getJSONObject("http_headers").optString("Cookie"); but would be helpful if that was in the library

**Comment by yausername** [comment]
Hi,
I have changed it to `Map<String, String>` in release `0.12.1`.
Let me know if that works.
Thanks

**Comment by swifityG** [comment]
yeah thanks, great work
