### ISSUE TITLE
Hey BRO My Reached Size Limit

### ISSUE THREAD

**Issue by shivam1608** [yausername/youtubedl-android#77]
Bro my app got upto 110MB and i used nothing just ffmpeg for mp3 and video one please can you tell me how can reduce the size of apk
![Annotation 2020-10-13 113909](https://user-images.githubusercontent.com/64302819/95822087-e5d9e180-0d48-11eb-85d1-d70064d2e878.png)

**Comment by xibr** [comment]
[51#issuecomment-631339951](https://github.com/yausername/youtubedl-android/issues/51#issuecomment-631339951)
