### ISSUE TITLE
Ability to get current version

### ISSUE THREAD

**Issue by Klemek** [yausername/youtubedl-android#8]
I encountered a youtube-dl related error [`"token" parameter not in video info`](https://github.com/ytdl-org/youtube-dl/issues/20761) which was fixed in a [recent pull request](https://github.com/ytdl-org/youtube-dl/pull/20770/commits/a8391b4648a1ba0fbc041adec07baeedaa456e0a) in the main repo. 

When I update with `YoutubeDL.getInstance().updateYoutubeDL(getApplication())` I get the code `ALREADY_UP_TO_DATE` and from your library api check, I get the right version from 30/04.

But how can I be sure that the current version I have is the correct one ? (In this case it seems it's not the correct version I have)
Could you add a `YoutubeDL.getInstance().getCurrentVersion(getApplication())` command ?
And by the way, In the `YoutubeDLUpdater.update` it seems to update shared preferences even if the download failed.

**Comment by yausername** [comment]
Hi @Klemek ,
I just made a release (0.5.0) with the latest youtubedl release. You might have to uninstall the app first before using this.

For getting the version of youtubedl you can use the below code - 
```java
YoutubeDLResponse response = YoutubeDL.getInstance().execute(new YoutubeDLRequest("").setOption("--version"));
System.out.println(response.getOut());
```



>  And by the way, In the `YoutubeDLUpdater.update` it seems to update shared preferences even if the download failed.

I don't see how this could happen. Can you give steps to reproduce or point me towards a bug in code?

Let me know if this does not solve your problem or if you have any other suggestions.
Thanks

**Comment by Klemek** [comment]
Thanks for the code example.
I was able to get it work by uninstalling completely my app then reinstalling it.

> I don't see how this could happen. Can you give steps to reproduce or point me towards a bug in code?
Sorry, in fact I skipped the part when you throw the caught exception. So I don't know what went wrong there.
