### ISSUE TITLE
How to use config file?

### ISSUE THREAD

**Issue by ganego** [yausername/youtubedl-android#85]
First of all, thank you, this is basically what I use on Android now to dl from video sites after Dentex (was forced to?) stop working on his app.

On my PC I can use a `config.txt` in `...\AppData\Roaming\youtube-dl` to set some settings (for example I don't want ytdl to change the modification date.

What folder should I use on android to do that? I have full root of course.

**Comment by yausername** [comment]
Do you use the custom command option?
In that case you can keep the file anywhere and provide its path in `--config-location`
Example - `--config-location /sdcard/.config/youtubedl/config`

**Comment by ganego** [comment]
No, I only use the download option. Since I just paste the video and press Enter. Want to keep it as simple as possible because I use it quite often.

**Comment by yausername** [comment]
Ok. It doesn't work in the download option atm.
Will fix and update.

**Comment by xibr** [comment]
@ganego Do you mean to add an option like this?
![Screenshot_20210501-000047_youtubedl-android-example.jpg](https://user-images.githubusercontent.com/20098154/116748873-23663980-aa11-11eb-8ef0-07b93e36b690.jpg)

In this case, you must create a config.txt file in the youtubedl-android directory and add some commands for example
```
--no-mtime

-o /sdcard/Download/youtubedl-android/%(title)s.%(ext)s

-f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"

```

If that's what you mean I can do that.

**Comment by ganego** [comment]
> Do you mean to add an option like this?

Pretty much, yes.

**Comment by xibr** [comment]
Well, if you only want to use this --no-mtime command we can add it, but if you want to use other commands we have to add what I suggested in the example in my comment above, @yausername What do you think?

**Comment by yausername** [comment]
@xibr what you suggested looks good to me. The ability to use a config file is a good feature to have.

**Comment by xibr** [comment]
done in [https://github.com/yausername/youtubedl-android/pull/106](https://github.com/yausername/youtubedl-android/pull/106)

**Comment by xibr** [comment]
@ganego you can find the latest debug APKs from here [https://github.com/yausername/youtubedl-android/releases/tag/0.12.4](https://github.com/yausername/youtubedl-android/releases/tag/0.12.4) or you can build one to use the config file when downloading from the download option.

**Comment by ganego** [comment]
I came around testing it now, sorry for the late reply.

There is one thing that should definitely be mentioned in the readme file for the config.txt part: You **have** to set the output folder/name manually or it will not work. Without `-o ...` I always get the following error ``ERROR: unable to open for writing: [Errno 30] Read-only file system: '<videoname>'``. 

Thank you for the feature.
