### ISSUE TITLE
Ability to cancel download

### ISSUE THREAD

**Issue by pheyse** [yausername/youtubedl-android#87]
Great library! :-) I would be happy if there was a way to cancel an ongoing download.
Maybe there aleady is a way which I don't know.

Otherwise it would be great if YoutubeDL.execute(YoutubeDLRequest request, DownloadProgressCallback callback) provide the process object. E.g. via another listener which would receive the process instance of if the callback instance would receive it or there could be a static field with a getter...

**Comment by xibr** [comment]
> Great library! :-) I would be happy if there was a way to cancel an ongoing download.
> Maybe there aleady is a way which I don't know.

Check this [#27](https://github.com/yausername/youtubedl-android/issues/27)

**Comment by pheyse** [comment]
Thanks!
