### ISSUE TITLE
Error updating youtube-dl

### ISSUE THREAD

**Issue by sindycarlo** [yausername/youtubedl-android#89]
hi,
i have this error on playing youtube video:
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
ERROR: Unable to download webpage: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(ConnectionResetError(104, 'Connection reset by peer')))

this may be caused by proxy or connection error?

thanks for the support.

**Comment by yausername** [comment]
Hi,
Can you check if the error is still happening?
There was a downtime on all google services. Might have been because of that.
