### ISSUE TITLE
Support for avconv

### ISSUE THREAD

**Issue by jefferson018200306** [yausername/youtubedl-android#94]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How can I set the avconv as the default merging tool?

I tried this on YouTube-dl debug app of yausername, and it says that FFmpeg is still working in the post processing files. Please add support on avconv, thanks!

**Comment by jefferson018200306** [comment]
Hi! Is there any updates?

**Comment by yausername** [comment]
Hi, I'm a little busy at the moment.
Won't be working on this soon.

**Comment by jefferson018200306** [comment]
> Hi, I'm a little busy at the moment.
> Won't be working on this soon.

It's okay, sorry for rushing you 😀

**Comment by xibr** [comment]
From https://github.com/yt-dlp/yt-dlp#deprecated 
> [avconv and avprobe](https://www.libav.org/) - Now deprecated alternative to ffmpeg. License [depends on the build](https://libav.org/legal)
